/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DTO for asset data.
 */
@ApiModel(description = "DTO for asset data.")

public class AssetDto
{
  public static final String SERIALIZED_NAME_SELECT_BY_ARTICLE_NUMBER = "selectByArticleNumber";
  @SerializedName(SERIALIZED_NAME_SELECT_BY_ARTICLE_NUMBER)
  private Boolean selectByArticleNumber;

  public static final String SERIALIZED_NAME_SELECT_FROM_MEDIA_POOL = "selectFromMediaPool";
  @SerializedName(SERIALIZED_NAME_SELECT_FROM_MEDIA_POOL)
  private Boolean selectFromMediaPool;

  public static final String SERIALIZED_NAME_FREE_TEXT_FIELD = "freeTextField";
  @SerializedName(SERIALIZED_NAME_FREE_TEXT_FIELD)
  private Integer freeTextField;


  public AssetDto selectByArticleNumber(Boolean selectByArticleNumber)
  {

    this.selectByArticleNumber = selectByArticleNumber;
    return this;
  }

  /**
   * @return selectByArticleNumber
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSelectByArticleNumber()
  {
    return selectByArticleNumber;
  }


  public void setSelectByArticleNumber(Boolean selectByArticleNumber)
  {
    this.selectByArticleNumber = selectByArticleNumber;
  }


  public AssetDto selectFromMediaPool(Boolean selectFromMediaPool)
  {

    this.selectFromMediaPool = selectFromMediaPool;
    return this;
  }

  /**
   * @return selectFromMediaPool
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSelectFromMediaPool()
  {
    return selectFromMediaPool;
  }


  public void setSelectFromMediaPool(Boolean selectFromMediaPool)
  {
    this.selectFromMediaPool = selectFromMediaPool;
  }


  public AssetDto freeTextField(Integer freeTextField)
  {

    this.freeTextField = freeTextField;
    return this;
  }

  /**
   * @return freeTextField
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getFreeTextField()
  {
    return freeTextField;
  }


  public void setFreeTextField(Integer freeTextField)
  {
    this.freeTextField = freeTextField;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    AssetDto assetDto = (AssetDto) o;
    return Objects.equals(this.selectByArticleNumber, assetDto.selectByArticleNumber) &&
            Objects.equals(this.selectFromMediaPool, assetDto.selectFromMediaPool) &&
            Objects.equals(this.freeTextField, assetDto.freeTextField);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(selectByArticleNumber, selectFromMediaPool, freeTextField);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetDto {\n");
    sb.append("    selectByArticleNumber: ").append(toIndentedString(selectByArticleNumber)).append("\n");
    sb.append("    selectFromMediaPool: ").append(toIndentedString(selectFromMediaPool)).append("\n");
    sb.append("    freeTextField: ").append(toIndentedString(freeTextField)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

