/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AssetSelectorColumnDtoAllOf
 */

public class AssetSelectorColumnDtoAllOf
{
  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  private Integer width;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private Integer position;

  public static final String SERIALIZED_NAME_ASSET = "asset";
  @SerializedName(SERIALIZED_NAME_ASSET)
  private AssetDto asset;

  public static final String SERIALIZED_NAME_FORMER_TECHNICAL_VALUE = "formerTechnicalValue";
  @SerializedName(SERIALIZED_NAME_FORMER_TECHNICAL_VALUE)
  private String formerTechnicalValue;

  public static final String SERIALIZED_NAME_DYNAMIC_TABLE_INDEX = "dynamicTableIndex";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_TABLE_INDEX)
  private String dynamicTableIndex;

  public static final String SERIALIZED_NAME_PREFILLING = "prefilling";
  @SerializedName(SERIALIZED_NAME_PREFILLING)
  private PrefillingDto prefilling;


  public AssetSelectorColumnDtoAllOf width(Integer width)
  {

    this.width = width;
    return this;
  }

  /**
   * @return width
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWidth()
  {
    return width;
  }


  public void setWidth(Integer width)
  {
    this.width = width;
  }


  public AssetSelectorColumnDtoAllOf position(Integer position)
  {

    this.position = position;
    return this;
  }

  /**
   * @return position
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPosition()
  {
    return position;
  }


  public void setPosition(Integer position)
  {
    this.position = position;
  }


  public AssetSelectorColumnDtoAllOf asset(AssetDto asset)
  {

    this.asset = asset;
    return this;
  }

  /**
   * Get asset
   *
   * @return asset
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AssetDto getAsset()
  {
    return asset;
  }


  public void setAsset(AssetDto asset)
  {
    this.asset = asset;
  }


  public AssetSelectorColumnDtoAllOf formerTechnicalValue(String formerTechnicalValue)
  {

    this.formerTechnicalValue = formerTechnicalValue;
    return this;
  }

  /**
   * @return formerTechnicalValue
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFormerTechnicalValue()
  {
    return formerTechnicalValue;
  }


  public void setFormerTechnicalValue(String formerTechnicalValue)
  {
    this.formerTechnicalValue = formerTechnicalValue;
  }


  public AssetSelectorColumnDtoAllOf dynamicTableIndex(String dynamicTableIndex)
  {

    this.dynamicTableIndex = dynamicTableIndex;
    return this;
  }

  /**
   * @return dynamicTableIndex
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDynamicTableIndex()
  {
    return dynamicTableIndex;
  }


  public void setDynamicTableIndex(String dynamicTableIndex)
  {
    this.dynamicTableIndex = dynamicTableIndex;
  }


  public AssetSelectorColumnDtoAllOf prefilling(PrefillingDto prefilling)
  {

    this.prefilling = prefilling;
    return this;
  }

  /**
   * Get prefilling
   *
   * @return prefilling
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PrefillingDto getPrefilling()
  {
    return prefilling;
  }


  public void setPrefilling(PrefillingDto prefilling)
  {
    this.prefilling = prefilling;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    AssetSelectorColumnDtoAllOf assetSelectorColumnDtoAllOf = (AssetSelectorColumnDtoAllOf) o;
    return Objects.equals(this.width, assetSelectorColumnDtoAllOf.width) &&
            Objects.equals(this.position, assetSelectorColumnDtoAllOf.position) &&
            Objects.equals(this.asset, assetSelectorColumnDtoAllOf.asset) &&
            Objects.equals(this.formerTechnicalValue, assetSelectorColumnDtoAllOf.formerTechnicalValue) &&
            Objects.equals(this.dynamicTableIndex, assetSelectorColumnDtoAllOf.dynamicTableIndex) &&
            Objects.equals(this.prefilling, assetSelectorColumnDtoAllOf.prefilling);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(width, position, asset, formerTechnicalValue, dynamicTableIndex, prefilling);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetSelectorColumnDtoAllOf {\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    formerTechnicalValue: ").append(toIndentedString(formerTechnicalValue)).append("\n");
    sb.append("    dynamicTableIndex: ").append(toIndentedString(dynamicTableIndex)).append("\n");
    sb.append("    prefilling: ").append(toIndentedString(prefilling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

