/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * BpmnWorkflowMetaInstanceAllOf
 */

public class BpmnWorkflowMetaInstanceAllOf
{
  public static final String SERIALIZED_NAME_XML = "xml";
  @SerializedName(SERIALIZED_NAME_XML)
  private String xml;


  public BpmnWorkflowMetaInstanceAllOf xml(String xml)
  {

    this.xml = xml;
    return this;
  }

  /**
   * @return xml
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getXml()
  {
    return xml;
  }


  public void setXml(String xml)
  {
    this.xml = xml;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    BpmnWorkflowMetaInstanceAllOf bpmnWorkflowMetaInstanceAllOf = (BpmnWorkflowMetaInstanceAllOf) o;
    return Objects.equals(this.xml, bpmnWorkflowMetaInstanceAllOf.xml);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(xml);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BpmnWorkflowMetaInstanceAllOf {\n");
    sb.append("    xml: ").append(toIndentedString(xml)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

