/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * BpmnWorkflowStepInstanceAllOf
 */

public class BpmnWorkflowStepInstanceAllOf
{
  public static final String SERIALIZED_NAME_USER_TASK_ID = "userTaskId";
  @SerializedName(SERIALIZED_NAME_USER_TASK_ID)
  private String userTaskId;


  public BpmnWorkflowStepInstanceAllOf userTaskId(String userTaskId)
  {

    this.userTaskId = userTaskId;
    return this;
  }

  /**
   * @return userTaskId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserTaskId()
  {
    return userTaskId;
  }


  public void setUserTaskId(String userTaskId)
  {
    this.userTaskId = userTaskId;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    BpmnWorkflowStepInstanceAllOf bpmnWorkflowStepInstanceAllOf = (BpmnWorkflowStepInstanceAllOf) o;
    return Objects.equals(this.userTaskId, bpmnWorkflowStepInstanceAllOf.userTaskId);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(userTaskId);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BpmnWorkflowStepInstanceAllOf {\n");
    sb.append("    userTaskId: ").append(toIndentedString(userTaskId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

