/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DTO for worflow step.
 */
@ApiModel(description = "DTO for worflow step.")

public class BreadcrumbWorkflowStepDetailsDto
{
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  private Integer number;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private LabelValueDto name;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private LabelValueDto startDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private LabelValueDto endDate;

  public static final String SERIALIZED_NAME_ASSIGNEES = "assignees";
  @SerializedName(SERIALIZED_NAME_ASSIGNEES)
  private LabelValueDto assignees;


  public BreadcrumbWorkflowStepDetailsDto id(Integer id)
  {

    this.id = id;
    return this;
  }

  /**
   * @return id
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId()
  {
    return id;
  }


  public void setId(Integer id)
  {
    this.id = id;
  }


  public BreadcrumbWorkflowStepDetailsDto number(Integer number)
  {

    this.number = number;
    return this;
  }

  /**
   * @return number
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNumber()
  {
    return number;
  }


  public void setNumber(Integer number)
  {
    this.number = number;
  }


  public BreadcrumbWorkflowStepDetailsDto name(LabelValueDto name)
  {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LabelValueDto getName()
  {
    return name;
  }


  public void setName(LabelValueDto name)
  {
    this.name = name;
  }


  public BreadcrumbWorkflowStepDetailsDto startDate(LabelValueDto startDate)
  {

    this.startDate = startDate;
    return this;
  }

  /**
   * Get startDate
   *
   * @return startDate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LabelValueDto getStartDate()
  {
    return startDate;
  }


  public void setStartDate(LabelValueDto startDate)
  {
    this.startDate = startDate;
  }


  public BreadcrumbWorkflowStepDetailsDto endDate(LabelValueDto endDate)
  {

    this.endDate = endDate;
    return this;
  }

  /**
   * Get endDate
   *
   * @return endDate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LabelValueDto getEndDate()
  {
    return endDate;
  }


  public void setEndDate(LabelValueDto endDate)
  {
    this.endDate = endDate;
  }


  public BreadcrumbWorkflowStepDetailsDto assignees(LabelValueDto assignees)
  {

    this.assignees = assignees;
    return this;
  }

  /**
   * Get assignees
   *
   * @return assignees
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LabelValueDto getAssignees()
  {
    return assignees;
  }


  public void setAssignees(LabelValueDto assignees)
  {
    this.assignees = assignees;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    BreadcrumbWorkflowStepDetailsDto breadcrumbWorkflowStepDetailsDto = (BreadcrumbWorkflowStepDetailsDto) o;
    return Objects.equals(this.id, breadcrumbWorkflowStepDetailsDto.id) &&
            Objects.equals(this.number, breadcrumbWorkflowStepDetailsDto.number) &&
            Objects.equals(this.name, breadcrumbWorkflowStepDetailsDto.name) &&
            Objects.equals(this.startDate, breadcrumbWorkflowStepDetailsDto.startDate) &&
            Objects.equals(this.endDate, breadcrumbWorkflowStepDetailsDto.endDate) &&
            Objects.equals(this.assignees, breadcrumbWorkflowStepDetailsDto.assignees);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(id, number, name, startDate, endDate, assignees);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BreadcrumbWorkflowStepDetailsDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

