/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CandidateGroupDefinitionErrorAllOf
 */

public class CandidateGroupDefinitionErrorAllOf
{
  public static final String SERIALIZED_NAME_AREA_I_DS = "areaIDs";
  @SerializedName(SERIALIZED_NAME_AREA_I_DS)
  private List<Integer> areaIDs = null;


  public CandidateGroupDefinitionErrorAllOf areaIDs(List<Integer> areaIDs)
  {

    this.areaIDs = areaIDs;
    return this;
  }

  public CandidateGroupDefinitionErrorAllOf addAreaIDsItem(Integer areaIDsItem)
  {
    if (this.areaIDs == null)
    {
      this.areaIDs = new ArrayList<Integer>();
    }
    this.areaIDs.add(areaIDsItem);
    return this;
  }

  /**
   * @return areaIDs
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getAreaIDs()
  {
    return areaIDs;
  }


  public void setAreaIDs(List<Integer> areaIDs)
  {
    this.areaIDs = areaIDs;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    CandidateGroupDefinitionErrorAllOf candidateGroupDefinitionErrorAllOf = (CandidateGroupDefinitionErrorAllOf) o;
    return Objects.equals(this.areaIDs, candidateGroupDefinitionErrorAllOf.areaIDs);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(areaIDs);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateGroupDefinitionErrorAllOf {\n");
    sb.append("    areaIDs: ").append(toIndentedString(areaIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

