/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ComfortGridDtoAllOf
 */

public class ComfortGridDtoAllOf
{
  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  private List<ComfortGridColumnRestDto> columns = null;

  public static final String SERIALIZED_NAME_PREFILLED_FROM_PARENT = "prefilledFromParent";
  @SerializedName(SERIALIZED_NAME_PREFILLED_FROM_PARENT)
  private Boolean prefilledFromParent;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "defaultValue";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  private String defaultValue;


  public ComfortGridDtoAllOf columns(List<ComfortGridColumnRestDto> columns)
  {

    this.columns = columns;
    return this;
  }

  public ComfortGridDtoAllOf addColumnsItem(ComfortGridColumnRestDto columnsItem)
  {
    if (this.columns == null)
    {
      this.columns = new ArrayList<ComfortGridColumnRestDto>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * @return columns
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ComfortGridColumnRestDto> getColumns()
  {
    return columns;
  }


  public void setColumns(List<ComfortGridColumnRestDto> columns)
  {
    this.columns = columns;
  }


  public ComfortGridDtoAllOf prefilledFromParent(Boolean prefilledFromParent)
  {

    this.prefilledFromParent = prefilledFromParent;
    return this;
  }

  /**
   * @return prefilledFromParent
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPrefilledFromParent()
  {
    return prefilledFromParent;
  }


  public void setPrefilledFromParent(Boolean prefilledFromParent)
  {
    this.prefilledFromParent = prefilledFromParent;
  }


  public ComfortGridDtoAllOf defaultValue(String defaultValue)
  {

    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * @return defaultValue
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDefaultValue()
  {
    return defaultValue;
  }


  public void setDefaultValue(String defaultValue)
  {
    this.defaultValue = defaultValue;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    ComfortGridDtoAllOf comfortGridDtoAllOf = (ComfortGridDtoAllOf) o;
    return Objects.equals(this.columns, comfortGridDtoAllOf.columns) &&
            Objects.equals(this.prefilledFromParent, comfortGridDtoAllOf.prefilledFromParent) &&
            Objects.equals(this.defaultValue, comfortGridDtoAllOf.defaultValue);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(columns, prefilledFromParent, defaultValue);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComfortGridDtoAllOf {\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    prefilledFromParent: ").append(toIndentedString(prefilledFromParent)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

