/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DTO for custom structure attribute.
 */
@ApiModel(description = "DTO for custom structure attribute.")

public class CustomStructureAttributeDto
{
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private Integer order;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public CustomStructureAttributeDto id(String id)
  {

    this.id = id;
    return this;
  }

  /**
   * @return id
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId()
  {
    return id;
  }


  public void setId(String id)
  {
    this.id = id;
  }


  public CustomStructureAttributeDto name(String name)
  {

    this.name = name;
    return this;
  }

  /**
   * @return name
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName()
  {
    return name;
  }


  public void setName(String name)
  {
    this.name = name;
  }


  public CustomStructureAttributeDto label(String label)
  {

    this.label = label;
    return this;
  }

  /**
   * @return label
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLabel()
  {
    return label;
  }


  public void setLabel(String label)
  {
    this.label = label;
  }


  public CustomStructureAttributeDto order(Integer order)
  {

    this.order = order;
    return this;
  }

  /**
   * @return order
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getOrder()
  {
    return order;
  }


  public void setOrder(Integer order)
  {
    this.order = order;
  }


  public CustomStructureAttributeDto comment(String comment)
  {

    this.comment = comment;
    return this;
  }

  /**
   * @return comment
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getComment()
  {
    return comment;
  }


  public void setComment(String comment)
  {
    this.comment = comment;
  }


  public CustomStructureAttributeDto type(String type)
  {

    this.type = type;
    return this;
  }

  /**
   * @return type
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getType()
  {
    return type;
  }


  public void setType(String type)
  {
    this.type = type;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    CustomStructureAttributeDto customStructureAttributeDto = (CustomStructureAttributeDto) o;
    return Objects.equals(this.id, customStructureAttributeDto.id) &&
            Objects.equals(this.name, customStructureAttributeDto.name) &&
            Objects.equals(this.label, customStructureAttributeDto.label) &&
            Objects.equals(this.order, customStructureAttributeDto.order) &&
            Objects.equals(this.comment, customStructureAttributeDto.comment) &&
            Objects.equals(this.type, customStructureAttributeDto.type);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(id, name, label, order, comment, type);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomStructureAttributeDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

