/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Lightweight data sheet
 */
@ApiModel(description = "Lightweight data sheet")

public class DataSheetLightDto
{
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_SECTIONS = "sections";
  @SerializedName(SERIALIZED_NAME_SECTIONS)
  private List<DataSheetSectionLightDto> sections = null;

  public static final String SERIALIZED_NAME_TECHNICAL_NAME = "technicalName";
  @SerializedName(SERIALIZED_NAME_TECHNICAL_NAME)
  private String technicalName;


  public DataSheetLightDto type(String type)
  {

    this.type = type;
    return this;
  }

  /**
   * @return type
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getType()
  {
    return type;
  }


  public void setType(String type)
  {
    this.type = type;
  }


  public DataSheetLightDto label(String label)
  {

    this.label = label;
    return this;
  }

  /**
   * @return label
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLabel()
  {
    return label;
  }


  public void setLabel(String label)
  {
    this.label = label;
  }


  public DataSheetLightDto sections(List<DataSheetSectionLightDto> sections)
  {

    this.sections = sections;
    return this;
  }

  public DataSheetLightDto addSectionsItem(DataSheetSectionLightDto sectionsItem)
  {
    if (this.sections == null)
    {
      this.sections = new ArrayList<DataSheetSectionLightDto>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

  /**
   * @return sections
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DataSheetSectionLightDto> getSections()
  {
    return sections;
  }


  public void setSections(List<DataSheetSectionLightDto> sections)
  {
    this.sections = sections;
  }


  public DataSheetLightDto technicalName(String technicalName)
  {

    this.technicalName = technicalName;
    return this;
  }

  /**
   * @return technicalName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTechnicalName()
  {
    return technicalName;
  }


  public void setTechnicalName(String technicalName)
  {
    this.technicalName = technicalName;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    DataSheetLightDto dataSheetLightDto = (DataSheetLightDto) o;
    return Objects.equals(this.type, dataSheetLightDto.type) &&
            Objects.equals(this.label, dataSheetLightDto.label) &&
            Objects.equals(this.sections, dataSheetLightDto.sections) &&
            Objects.equals(this.technicalName, dataSheetLightDto.technicalName);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(type, label, sections, technicalName);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataSheetLightDto {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("    technicalName: ").append(toIndentedString(technicalName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

