/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Lightweight data sheet section
 */
@ApiModel(description = "Lightweight data sheet section")

public class DataSheetSectionLightDto
{
  public static final String SERIALIZED_NAME_AREAS = "areas";
  @SerializedName(SERIALIZED_NAME_AREAS)
  private List<DataSheetAreaLightDto> areas = null;


  public DataSheetSectionLightDto areas(List<DataSheetAreaLightDto> areas)
  {

    this.areas = areas;
    return this;
  }

  public DataSheetSectionLightDto addAreasItem(DataSheetAreaLightDto areasItem)
  {
    if (this.areas == null)
    {
      this.areas = new ArrayList<DataSheetAreaLightDto>();
    }
    this.areas.add(areasItem);
    return this;
  }

  /**
   * @return areas
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DataSheetAreaLightDto> getAreas()
  {
    return areas;
  }


  public void setAreas(List<DataSheetAreaLightDto> areas)
  {
    this.areas = areas;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    DataSheetSectionLightDto dataSheetSectionLightDto = (DataSheetSectionLightDto) o;
    return Objects.equals(this.areas, dataSheetSectionLightDto.areas);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(areas);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataSheetSectionLightDto {\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

