/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * DTO for document selector variable type.
 */
@ApiModel(description = "DTO for document selector variable type.")

public class DocumentSelectorDto
{
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;

    public static final String SERIALIZED_NAME_META_TYPE_ID = "metaTypeId";
    @SerializedName(SERIALIZED_NAME_META_TYPE_ID)
    private Integer metaTypeId;

    public static final String SERIALIZED_NAME_META_TYPE_NAME = "metaTypeName";
    @SerializedName(SERIALIZED_NAME_META_TYPE_NAME)
    private String metaTypeName;

    public static final String SERIALIZED_NAME_UNIQUE_NAME = "uniqueName";
    @SerializedName(SERIALIZED_NAME_UNIQUE_NAME)
    private String uniqueName;

    public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
    @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
    private String displayName;

    public static final String SERIALIZED_NAME_RAW_LABEL = "rawLabel";
    @SerializedName(SERIALIZED_NAME_RAW_LABEL)
    private String rawLabel;

    public static final String SERIALIZED_NAME_MODE = "mode";
    @SerializedName(SERIALIZED_NAME_MODE)
    private Integer mode;

    public static final String SERIALIZED_NAME_TECHNICAL_NAME = "technicalName";
    @SerializedName(SERIALIZED_NAME_TECHNICAL_NAME)
    private String technicalName;

    public static final String SERIALIZED_NAME_SHARED_LOCALE = "sharedLocale";
    @SerializedName(SERIALIZED_NAME_SHARED_LOCALE)
    private Boolean sharedLocale;

    public static final String SERIALIZED_NAME_HELP_TEXT = "helpText";
    @SerializedName(SERIALIZED_NAME_HELP_TEXT)
    private String helpText;

    public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
    @SerializedName(SERIALIZED_NAME_VISIBILITY)
    private VisibilityDto visibility;

    public static final String SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_ID = "dependsFromVariableId";
    @SerializedName(SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_ID)
    private Integer dependsFromVariableId;

    public static final String SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_VALUES = "dependsFromVariableValues";
    @SerializedName(SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_VALUES)
    private List<String> dependsFromVariableValues = null;

    public static final String SERIALIZED_NAME_TYPE_SPANNING = "typeSpanning";
    @SerializedName(SERIALIZED_NAME_TYPE_SPANNING)
    private Boolean typeSpanning;

    public static final String SERIALIZED_NAME_SYSTEM = "system";
    @SerializedName(SERIALIZED_NAME_SYSTEM)
    private Boolean system;

    public static final String SERIALIZED_NAME_STORAGE_TYPE = "storageType";
    @SerializedName(SERIALIZED_NAME_STORAGE_TYPE)
    private Integer storageType;

    public static final String SERIALIZED_NAME_INHERIT_FROM_PARENT = "inheritFromParent";
    @SerializedName(SERIALIZED_NAME_INHERIT_FROM_PARENT)
    private Boolean inheritFromParent;


    public DocumentSelectorDto id(Integer id)
    {

        this.id = id;
        return this;
    }

    /**
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getId()
    {
        return id;
    }


    public void setId(Integer id)
    {
        this.id = id;
    }


    public DocumentSelectorDto metaTypeId(Integer metaTypeId)
    {

        this.metaTypeId = metaTypeId;
        return this;
    }

    /**
     * @return metaTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMetaTypeId()
    {
        return metaTypeId;
    }


    public void setMetaTypeId(Integer metaTypeId)
    {
        this.metaTypeId = metaTypeId;
    }


    public DocumentSelectorDto metaTypeName(String metaTypeName)
    {

        this.metaTypeName = metaTypeName;
        return this;
    }

    /**
     * @return metaTypeName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getMetaTypeName()
    {
        return metaTypeName;
    }


    public void setMetaTypeName(String metaTypeName)
    {
        this.metaTypeName = metaTypeName;
    }


    public DocumentSelectorDto uniqueName(String uniqueName)
    {

        this.uniqueName = uniqueName;
        return this;
    }

    /**
     * @return uniqueName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getUniqueName()
    {
        return uniqueName;
    }


    public void setUniqueName(String uniqueName)
    {
        this.uniqueName = uniqueName;
    }


    public DocumentSelectorDto displayName(String displayName)
    {

        this.displayName = displayName;
        return this;
    }

    /**
     * @return displayName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDisplayName()
    {
        return displayName;
    }


    public void setDisplayName(String displayName)
    {
        this.displayName = displayName;
    }


    public DocumentSelectorDto rawLabel(String rawLabel)
    {

        this.rawLabel = rawLabel;
        return this;
    }

    /**
     * @return rawLabel
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getRawLabel()
    {
        return rawLabel;
    }


    public void setRawLabel(String rawLabel)
    {
        this.rawLabel = rawLabel;
    }


    public DocumentSelectorDto mode(Integer mode)
    {

        this.mode = mode;
        return this;
    }

    /**
     * @return mode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMode()
    {
        return mode;
    }


    public void setMode(Integer mode)
    {
        this.mode = mode;
    }


    public DocumentSelectorDto technicalName(String technicalName)
    {

        this.technicalName = technicalName;
        return this;
    }

    /**
     * @return technicalName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getTechnicalName()
    {
        return technicalName;
    }


    public void setTechnicalName(String technicalName)
    {
        this.technicalName = technicalName;
    }


    public DocumentSelectorDto sharedLocale(Boolean sharedLocale)
    {

        this.sharedLocale = sharedLocale;
        return this;
    }

    /**
     * @return sharedLocale
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getSharedLocale()
    {
        return sharedLocale;
    }


    public void setSharedLocale(Boolean sharedLocale)
    {
        this.sharedLocale = sharedLocale;
    }


    public DocumentSelectorDto helpText(String helpText)
    {

        this.helpText = helpText;
        return this;
    }

    /**
     * @return helpText
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getHelpText()
    {
        return helpText;
    }


    public void setHelpText(String helpText)
    {
        this.helpText = helpText;
    }


    public DocumentSelectorDto visibility(VisibilityDto visibility)
    {

        this.visibility = visibility;
        return this;
    }

    /**
     * Get visibility
     *
     * @return visibility
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public VisibilityDto getVisibility()
    {
        return visibility;
    }


    public void setVisibility(VisibilityDto visibility)
    {
        this.visibility = visibility;
    }


    public DocumentSelectorDto dependsFromVariableId(Integer dependsFromVariableId)
    {

        this.dependsFromVariableId = dependsFromVariableId;
        return this;
    }

    /**
     * @return dependsFromVariableId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getDependsFromVariableId()
    {
        return dependsFromVariableId;
    }


    public void setDependsFromVariableId(Integer dependsFromVariableId)
    {
        this.dependsFromVariableId = dependsFromVariableId;
    }


    public DocumentSelectorDto dependsFromVariableValues(List<String> dependsFromVariableValues)
    {

        this.dependsFromVariableValues = dependsFromVariableValues;
        return this;
    }

    public DocumentSelectorDto addDependsFromVariableValuesItem(String dependsFromVariableValuesItem)
    {
        if (this.dependsFromVariableValues == null)
        {
            this.dependsFromVariableValues = new ArrayList<String>();
        }
        this.dependsFromVariableValues.add(dependsFromVariableValuesItem);
        return this;
    }

    /**
     * @return dependsFromVariableValues
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getDependsFromVariableValues()
    {
        return dependsFromVariableValues;
    }


    public void setDependsFromVariableValues(List<String> dependsFromVariableValues)
    {
        this.dependsFromVariableValues = dependsFromVariableValues;
    }


    public DocumentSelectorDto typeSpanning(Boolean typeSpanning)
    {

        this.typeSpanning = typeSpanning;
        return this;
    }

    /**
     * @return typeSpanning
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getTypeSpanning()
    {
        return typeSpanning;
    }


    public void setTypeSpanning(Boolean typeSpanning)
    {
        this.typeSpanning = typeSpanning;
    }


    public DocumentSelectorDto system(Boolean system)
    {

        this.system = system;
        return this;
    }

    /**
     * @return system
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getSystem()
    {
        return system;
    }


    public void setSystem(Boolean system)
    {
        this.system = system;
    }


    public DocumentSelectorDto storageType(Integer storageType)
    {

        this.storageType = storageType;
        return this;
    }

    /**
     * @return storageType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getStorageType()
    {
        return storageType;
    }


    public void setStorageType(Integer storageType)
    {
        this.storageType = storageType;
    }


    public DocumentSelectorDto inheritFromParent(Boolean inheritFromParent)
    {

        this.inheritFromParent = inheritFromParent;
        return this;
    }

    /**
     * @return inheritFromParent
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getInheritFromParent()
    {
        return inheritFromParent;
    }


    public void setInheritFromParent(Boolean inheritFromParent)
    {
        this.inheritFromParent = inheritFromParent;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DocumentSelectorDto documentSelectorDto = (DocumentSelectorDto) o;
        return Objects.equals(this.id, documentSelectorDto.id) &&
                Objects.equals(this.metaTypeId, documentSelectorDto.metaTypeId) &&
                Objects.equals(this.metaTypeName, documentSelectorDto.metaTypeName) &&
                Objects.equals(this.uniqueName, documentSelectorDto.uniqueName) &&
                Objects.equals(this.displayName, documentSelectorDto.displayName) &&
                Objects.equals(this.rawLabel, documentSelectorDto.rawLabel) &&
                Objects.equals(this.mode, documentSelectorDto.mode) &&
                Objects.equals(this.technicalName, documentSelectorDto.technicalName) &&
                Objects.equals(this.sharedLocale, documentSelectorDto.sharedLocale) &&
                Objects.equals(this.helpText, documentSelectorDto.helpText) &&
                Objects.equals(this.visibility, documentSelectorDto.visibility) &&
                Objects.equals(this.dependsFromVariableId, documentSelectorDto.dependsFromVariableId) &&
                Objects.equals(this.dependsFromVariableValues, documentSelectorDto.dependsFromVariableValues) &&
                Objects.equals(this.typeSpanning, documentSelectorDto.typeSpanning) &&
                Objects.equals(this.system, documentSelectorDto.system) &&
                Objects.equals(this.storageType, documentSelectorDto.storageType) &&
                Objects.equals(this.inheritFromParent, documentSelectorDto.inheritFromParent);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(id, metaTypeId, metaTypeName, uniqueName, displayName, rawLabel, mode, technicalName, sharedLocale, helpText, visibility, dependsFromVariableId, dependsFromVariableValues, typeSpanning, system, storageType, inheritFromParent);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DocumentSelectorDto {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    metaTypeId: ").append(toIndentedString(metaTypeId)).append("\n");
        sb.append("    metaTypeName: ").append(toIndentedString(metaTypeName)).append("\n");
        sb.append("    uniqueName: ").append(toIndentedString(uniqueName)).append("\n");
        sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
        sb.append("    rawLabel: ").append(toIndentedString(rawLabel)).append("\n");
        sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
        sb.append("    technicalName: ").append(toIndentedString(technicalName)).append("\n");
        sb.append("    sharedLocale: ").append(toIndentedString(sharedLocale)).append("\n");
        sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
        sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
        sb.append("    dependsFromVariableId: ").append(toIndentedString(dependsFromVariableId)).append("\n");
        sb.append("    dependsFromVariableValues: ").append(toIndentedString(dependsFromVariableValues)).append("\n");
        sb.append("    typeSpanning: ").append(toIndentedString(typeSpanning)).append("\n");
        sb.append("    system: ").append(toIndentedString(system)).append("\n");
        sb.append("    storageType: ").append(toIndentedString(storageType)).append("\n");
        sb.append("    inheritFromParent: ").append(toIndentedString(inheritFromParent)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

