/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;

/**
 * DSE BPMN object
 */
@ApiModel(description = "DSE BPMN object")

public class DseBpmnObjectDto
{
    public static final String SERIALIZED_NAME_VALUES = "values";
    @SerializedName(SERIALIZED_NAME_VALUES)
    private Map<String, DseBpmnObjectValueDto> values = null;

    public static final String SERIALIZED_NAME_INSTANCE_ID = "instanceId";
    @SerializedName(SERIALIZED_NAME_INSTANCE_ID)
    private Integer instanceId;

    public static final String SERIALIZED_NAME_L10N_LOCALE_ID = "l10nLocaleId";
    @SerializedName(SERIALIZED_NAME_L10N_LOCALE_ID)
    private Integer l10nLocaleId;

    public static final String SERIALIZED_NAME_WORKFLOW_OBJECT_ID = "workflowObjectId";
    @SerializedName(SERIALIZED_NAME_WORKFLOW_OBJECT_ID)
    private Integer workflowObjectId;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public static final String SERIALIZED_NAME_EXTENDED_NAME = "extendedName";
    @SerializedName(SERIALIZED_NAME_EXTENDED_NAME)
    private String extendedName;

    public static final String SERIALIZED_NAME_STATE = "state";
    @SerializedName(SERIALIZED_NAME_STATE)
    private String state;

    public static final String SERIALIZED_NAME_ORDINAL_NUMBER = "ordinalNumber";
    @SerializedName(SERIALIZED_NAME_ORDINAL_NUMBER)
    private Integer ordinalNumber;

    public static final String SERIALIZED_NAME_TYPE_ID = "typeId";
    @SerializedName(SERIALIZED_NAME_TYPE_ID)
    private Integer typeId;

    public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
    @SerializedName(SERIALIZED_NAME_CREATED_BY)
    private String createdBy;

    public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
    @SerializedName(SERIALIZED_NAME_PARENT_ID)
    private Integer parentId;

    public static final String SERIALIZED_NAME_CREATOR = "creator";
    @SerializedName(SERIALIZED_NAME_CREATOR)
    private UserDto creator;

    public static final String SERIALIZED_NAME_WORKFLOW_TYPE_ID = "workflowTypeId";
    @SerializedName(SERIALIZED_NAME_WORKFLOW_TYPE_ID)
    private Integer workflowTypeId;

    public static final String SERIALIZED_NAME_DSE_OBJECT_TYPE_ID = "dseObjectTypeId";
    @SerializedName(SERIALIZED_NAME_DSE_OBJECT_TYPE_ID)
    private Integer dseObjectTypeId;


    public DseBpmnObjectDto values(Map<String, DseBpmnObjectValueDto> values)
    {

        this.values = values;
        return this;
    }

    public DseBpmnObjectDto putValuesItem(String key, DseBpmnObjectValueDto valuesItem)
    {
        if (this.values == null)
        {
            this.values = new HashMap<String, DseBpmnObjectValueDto>();
        }
        this.values.put(key, valuesItem);
        return this;
    }

    /**
     * @return values
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Map<String, DseBpmnObjectValueDto> getValues()
    {
        return values;
    }


    public void setValues(Map<String, DseBpmnObjectValueDto> values)
    {
        this.values = values;
    }


    public DseBpmnObjectDto instanceId(Integer instanceId)
    {

        this.instanceId = instanceId;
        return this;
    }

    /**
     * @return instanceId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getInstanceId()
    {
        return instanceId;
    }


    public void setInstanceId(Integer instanceId)
    {
        this.instanceId = instanceId;
    }


    public DseBpmnObjectDto l10nLocaleId(Integer l10nLocaleId)
    {

        this.l10nLocaleId = l10nLocaleId;
        return this;
    }

    /**
     * @return l10nLocaleId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getL10nLocaleId()
    {
        return l10nLocaleId;
    }


    public void setL10nLocaleId(Integer l10nLocaleId)
    {
        this.l10nLocaleId = l10nLocaleId;
    }


    public DseBpmnObjectDto workflowObjectId(Integer workflowObjectId)
    {

        this.workflowObjectId = workflowObjectId;
        return this;
    }

    /**
     * @return workflowObjectId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWorkflowObjectId()
    {
        return workflowObjectId;
    }


    public void setWorkflowObjectId(Integer workflowObjectId)
    {
        this.workflowObjectId = workflowObjectId;
    }


    public DseBpmnObjectDto name(String name)
    {

        this.name = name;
        return this;
    }

    /**
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getName()
    {
        return name;
    }


    public void setName(String name)
    {
        this.name = name;
    }


    public DseBpmnObjectDto extendedName(String extendedName)
    {

        this.extendedName = extendedName;
        return this;
    }

    /**
     * @return extendedName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getExtendedName()
    {
        return extendedName;
    }


    public void setExtendedName(String extendedName)
    {
        this.extendedName = extendedName;
    }


    public DseBpmnObjectDto state(String state)
    {

        this.state = state;
        return this;
    }

    /**
     * @return state
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getState()
    {
        return state;
    }


    public void setState(String state)
    {
        this.state = state;
    }


    public DseBpmnObjectDto ordinalNumber(Integer ordinalNumber)
    {

        this.ordinalNumber = ordinalNumber;
        return this;
    }

    /**
     * @return ordinalNumber
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getOrdinalNumber()
    {
        return ordinalNumber;
    }


    public void setOrdinalNumber(Integer ordinalNumber)
    {
        this.ordinalNumber = ordinalNumber;
    }


    public DseBpmnObjectDto typeId(Integer typeId)
    {

        this.typeId = typeId;
        return this;
    }

    /**
     * @return typeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getTypeId()
    {
        return typeId;
    }


    public void setTypeId(Integer typeId)
    {
        this.typeId = typeId;
    }


    public DseBpmnObjectDto createdBy(String createdBy)
    {

        this.createdBy = createdBy;
        return this;
    }

    /**
     * @return createdBy
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getCreatedBy()
    {
        return createdBy;
    }


    public void setCreatedBy(String createdBy)
    {
        this.createdBy = createdBy;
    }


    public DseBpmnObjectDto parentId(Integer parentId)
    {

        this.parentId = parentId;
        return this;
    }

    /**
     * @return parentId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getParentId()
    {
        return parentId;
    }


    public void setParentId(Integer parentId)
    {
        this.parentId = parentId;
    }


    public DseBpmnObjectDto creator(UserDto creator)
    {

        this.creator = creator;
        return this;
    }

    /**
     * Get creator
     *
     * @return creator
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public UserDto getCreator()
    {
        return creator;
    }


    public void setCreator(UserDto creator)
    {
        this.creator = creator;
    }


    public DseBpmnObjectDto workflowTypeId(Integer workflowTypeId)
    {

        this.workflowTypeId = workflowTypeId;
        return this;
    }

    /**
     * @return workflowTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWorkflowTypeId()
    {
        return workflowTypeId;
    }


    public void setWorkflowTypeId(Integer workflowTypeId)
    {
        this.workflowTypeId = workflowTypeId;
    }


    public DseBpmnObjectDto dseObjectTypeId(Integer dseObjectTypeId)
    {

        this.dseObjectTypeId = dseObjectTypeId;
        return this;
    }

    /**
     * @return dseObjectTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getDseObjectTypeId()
    {
        return dseObjectTypeId;
    }


    public void setDseObjectTypeId(Integer dseObjectTypeId)
    {
        this.dseObjectTypeId = dseObjectTypeId;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DseBpmnObjectDto dseBpmnObjectDto = (DseBpmnObjectDto) o;
        return Objects.equals(this.values, dseBpmnObjectDto.values) &&
                Objects.equals(this.instanceId, dseBpmnObjectDto.instanceId) &&
                Objects.equals(this.l10nLocaleId, dseBpmnObjectDto.l10nLocaleId) &&
                Objects.equals(this.workflowObjectId, dseBpmnObjectDto.workflowObjectId) &&
                Objects.equals(this.name, dseBpmnObjectDto.name) &&
                Objects.equals(this.extendedName, dseBpmnObjectDto.extendedName) &&
                Objects.equals(this.state, dseBpmnObjectDto.state) &&
                Objects.equals(this.ordinalNumber, dseBpmnObjectDto.ordinalNumber) &&
                Objects.equals(this.typeId, dseBpmnObjectDto.typeId) &&
                Objects.equals(this.createdBy, dseBpmnObjectDto.createdBy) &&
                Objects.equals(this.parentId, dseBpmnObjectDto.parentId) &&
                Objects.equals(this.creator, dseBpmnObjectDto.creator) &&
                Objects.equals(this.workflowTypeId, dseBpmnObjectDto.workflowTypeId) &&
                Objects.equals(this.dseObjectTypeId, dseBpmnObjectDto.dseObjectTypeId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(values, instanceId, l10nLocaleId, workflowObjectId, name, extendedName, state, ordinalNumber, typeId, createdBy, parentId, creator, workflowTypeId, dseObjectTypeId);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DseBpmnObjectDto {\n");
        sb.append("    values: ").append(toIndentedString(values)).append("\n");
        sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
        sb.append("    l10nLocaleId: ").append(toIndentedString(l10nLocaleId)).append("\n");
        sb.append("    workflowObjectId: ").append(toIndentedString(workflowObjectId)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    extendedName: ").append(toIndentedString(extendedName)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    ordinalNumber: ").append(toIndentedString(ordinalNumber)).append("\n");
        sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
        sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
        sb.append("    workflowTypeId: ").append(toIndentedString(workflowTypeId)).append("\n");
        sb.append("    dseObjectTypeId: ").append(toIndentedString(dseObjectTypeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

