/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DSE BPMN object value
 */
@ApiModel(description = "DSE BPMN object value")

public class DseBpmnObjectValueDto
{
    public static final String SERIALIZED_NAME_INHERIT_FROM_PARENT = "inheritFromParent";
    @SerializedName(SERIALIZED_NAME_INHERIT_FROM_PARENT)
    private InheritFromParentEnum inheritFromParent;

    public static final String SERIALIZED_NAME_INHERITED_VALUE = "inheritedValue";
    @SerializedName(SERIALIZED_NAME_INHERITED_VALUE)
    private String inheritedValue;

    public static final String SERIALIZED_NAME_DISPLAY_VALUE = "displayValue";
    @SerializedName(SERIALIZED_NAME_DISPLAY_VALUE)
    private String displayValue;

    public static final String SERIALIZED_NAME_VALUE = "value";
    @SerializedName(SERIALIZED_NAME_VALUE)
    private Object value;

    public static final String SERIALIZED_NAME_META_TYPE_ID = "metaTypeId";
    @SerializedName(SERIALIZED_NAME_META_TYPE_ID)
    private Integer metaTypeId;


    public DseBpmnObjectValueDto inheritFromParent(InheritFromParentEnum inheritFromParent)
    {

        this.inheritFromParent = inheritFromParent;
        return this;
    }

    /**
     * Get inheritFromParent
     *
     * @return inheritFromParent
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public InheritFromParentEnum getInheritFromParent()
    {
        return inheritFromParent;
    }


    public void setInheritFromParent(InheritFromParentEnum inheritFromParent)
    {
        this.inheritFromParent = inheritFromParent;
    }


    public DseBpmnObjectValueDto inheritedValue(String inheritedValue)
    {

        this.inheritedValue = inheritedValue;
        return this;
    }

    /**
     * @return inheritedValue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getInheritedValue()
    {
        return inheritedValue;
    }


    public void setInheritedValue(String inheritedValue)
    {
        this.inheritedValue = inheritedValue;
    }


    public DseBpmnObjectValueDto displayValue(String displayValue)
    {

        this.displayValue = displayValue;
        return this;
    }

    /**
     * @return displayValue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDisplayValue()
    {
        return displayValue;
    }


    public void setDisplayValue(String displayValue)
    {
        this.displayValue = displayValue;
    }


    public DseBpmnObjectValueDto value(Object value)
    {

        this.value = value;
        return this;
    }

    /**
     * @return value
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Object getValue()
    {
        return value;
    }


    public void setValue(Object value)
    {
        this.value = value;
    }


    public DseBpmnObjectValueDto metaTypeId(Integer metaTypeId)
    {

        this.metaTypeId = metaTypeId;
        return this;
    }

    /**
     * @return metaTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMetaTypeId()
    {
        return metaTypeId;
    }


    public void setMetaTypeId(Integer metaTypeId)
    {
        this.metaTypeId = metaTypeId;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DseBpmnObjectValueDto dseBpmnObjectValueDto = (DseBpmnObjectValueDto) o;
        return Objects.equals(this.inheritFromParent, dseBpmnObjectValueDto.inheritFromParent) &&
                Objects.equals(this.inheritedValue, dseBpmnObjectValueDto.inheritedValue) &&
                Objects.equals(this.displayValue, dseBpmnObjectValueDto.displayValue) &&
                Objects.equals(this.value, dseBpmnObjectValueDto.value) &&
                Objects.equals(this.metaTypeId, dseBpmnObjectValueDto.metaTypeId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(inheritFromParent, inheritedValue, displayValue, value, metaTypeId);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DseBpmnObjectValueDto {\n");
        sb.append("    inheritFromParent: ").append(toIndentedString(inheritFromParent)).append("\n");
        sb.append("    inheritedValue: ").append(toIndentedString(inheritedValue)).append("\n");
        sb.append("    displayValue: ").append(toIndentedString(displayValue)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    metaTypeId: ").append(toIndentedString(metaTypeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

