/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 *
 */
@ApiModel(description = "")

public class DseMaplParentVariable
{
    public static final String SERIALIZED_NAME_PARENT_NODE_ID = "parentNodeId";
    @SerializedName(SERIALIZED_NAME_PARENT_NODE_ID)
    private Integer parentNodeId;

    public static final String SERIALIZED_NAME_START_DATE = "startDate";
    @SerializedName(SERIALIZED_NAME_START_DATE)
    private Integer startDate;

    public static final String SERIALIZED_NAME_END_DATE = "endDate";
    @SerializedName(SERIALIZED_NAME_END_DATE)
    private Integer endDate;


    public DseMaplParentVariable parentNodeId(Integer parentNodeId)
    {

        this.parentNodeId = parentNodeId;
        return this;
    }

    /**
     * @return parentNodeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getParentNodeId()
    {
        return parentNodeId;
    }


    public void setParentNodeId(Integer parentNodeId)
    {
        this.parentNodeId = parentNodeId;
    }


    public DseMaplParentVariable startDate(Integer startDate)
    {

        this.startDate = startDate;
        return this;
    }

    /**
     * @return startDate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getStartDate()
    {
        return startDate;
    }


    public void setStartDate(Integer startDate)
    {
        this.startDate = startDate;
    }


    public DseMaplParentVariable endDate(Integer endDate)
    {

        this.endDate = endDate;
        return this;
    }

    /**
     * @return endDate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getEndDate()
    {
        return endDate;
    }


    public void setEndDate(Integer endDate)
    {
        this.endDate = endDate;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DseMaplParentVariable dseMaplParentVariable = (DseMaplParentVariable) o;
        return Objects.equals(this.parentNodeId, dseMaplParentVariable.parentNodeId) &&
                Objects.equals(this.startDate, dseMaplParentVariable.startDate) &&
                Objects.equals(this.endDate, dseMaplParentVariable.endDate);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(parentNodeId, startDate, endDate);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DseMaplParentVariable {\n");
        sb.append("    parentNodeId: ").append(toIndentedString(parentNodeId)).append("\n");
        sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
        sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

