/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 *
 */
@ApiModel(description = "")

public class DseMaplSyncConfigDto
{
    public static final String SERIALIZED_NAME_PARENT_TREE = "parentTree";
    @SerializedName(SERIALIZED_NAME_PARENT_TREE)
    private List<DseMaplParentTreeDto> parentTree = null;

    public static final String SERIALIZED_NAME_MAPPING_CONFIG = "mappingConfig";
    @SerializedName(SERIALIZED_NAME_MAPPING_CONFIG)
    private DseMaplMappingConfigDto mappingConfig;

    public static final String SERIALIZED_NAME_PLANNED_BUDGET_ENABLED = "plannedBudgetEnabled";
    @SerializedName(SERIALIZED_NAME_PLANNED_BUDGET_ENABLED)
    private Boolean plannedBudgetEnabled;

    public static final String SERIALIZED_NAME_TIMELINES_ENABLED = "timelinesEnabled";
    @SerializedName(SERIALIZED_NAME_TIMELINES_ENABLED)
    private Boolean timelinesEnabled;


    public DseMaplSyncConfigDto parentTree(List<DseMaplParentTreeDto> parentTree)
    {

        this.parentTree = parentTree;
        return this;
    }

    public DseMaplSyncConfigDto addParentTreeItem(DseMaplParentTreeDto parentTreeItem)
    {
        if (this.parentTree == null)
        {
            this.parentTree = new ArrayList<DseMaplParentTreeDto>();
        }
        this.parentTree.add(parentTreeItem);
        return this;
    }

    /**
     * @return parentTree
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<DseMaplParentTreeDto> getParentTree()
    {
        return parentTree;
    }


    public void setParentTree(List<DseMaplParentTreeDto> parentTree)
    {
        this.parentTree = parentTree;
    }


    public DseMaplSyncConfigDto mappingConfig(DseMaplMappingConfigDto mappingConfig)
    {

        this.mappingConfig = mappingConfig;
        return this;
    }

    /**
     * Get mappingConfig
     *
     * @return mappingConfig
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public DseMaplMappingConfigDto getMappingConfig()
    {
        return mappingConfig;
    }


    public void setMappingConfig(DseMaplMappingConfigDto mappingConfig)
    {
        this.mappingConfig = mappingConfig;
    }


    public DseMaplSyncConfigDto plannedBudgetEnabled(Boolean plannedBudgetEnabled)
    {

        this.plannedBudgetEnabled = plannedBudgetEnabled;
        return this;
    }

    /**
     * @return plannedBudgetEnabled
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getPlannedBudgetEnabled()
    {
        return plannedBudgetEnabled;
    }


    public void setPlannedBudgetEnabled(Boolean plannedBudgetEnabled)
    {
        this.plannedBudgetEnabled = plannedBudgetEnabled;
    }


    public DseMaplSyncConfigDto timelinesEnabled(Boolean timelinesEnabled)
    {

        this.timelinesEnabled = timelinesEnabled;
        return this;
    }

    /**
     * @return timelinesEnabled
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getTimelinesEnabled()
    {
        return timelinesEnabled;
    }


    public void setTimelinesEnabled(Boolean timelinesEnabled)
    {
        this.timelinesEnabled = timelinesEnabled;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DseMaplSyncConfigDto dseMaplSyncConfigDto = (DseMaplSyncConfigDto) o;
        return Objects.equals(this.parentTree, dseMaplSyncConfigDto.parentTree) &&
                Objects.equals(this.mappingConfig, dseMaplSyncConfigDto.mappingConfig) &&
                Objects.equals(this.plannedBudgetEnabled, dseMaplSyncConfigDto.plannedBudgetEnabled) &&
                Objects.equals(this.timelinesEnabled, dseMaplSyncConfigDto.timelinesEnabled);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(parentTree, mappingConfig, plannedBudgetEnabled, timelinesEnabled);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DseMaplSyncConfigDto {\n");
        sb.append("    parentTree: ").append(toIndentedString(parentTree)).append("\n");
        sb.append("    mappingConfig: ").append(toIndentedString(mappingConfig)).append("\n");
        sb.append("    plannedBudgetEnabled: ").append(toIndentedString(plannedBudgetEnabled)).append("\n");
        sb.append("    timelinesEnabled: ").append(toIndentedString(timelinesEnabled)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

