/*
 * DSE REST INTERNAL API
 * <h2>DSE REST INTERNAL API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Properties for dse object type entity
 */
@ApiModel(description = "Properties for dse object type entity")

public class DseObjectTypeAdminMinDto
{
    public static final String SERIALIZED_NAME_BRIEFING = "briefing";
    @SerializedName(SERIALIZED_NAME_BRIEFING)
    private Boolean briefing;

    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;

    public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
    @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
    private String displayName;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";
    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    private String description;

    public static final String SERIALIZED_NAME_RUN_MODULE = "runModule";


    public DseObjectTypeAdminMinDto briefing(Boolean briefing)
    {

        this.briefing = briefing;
        return this;
    }

    /**
     * Get briefing
     *
     * @return briefing
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getBriefing()
    {
        return briefing;
    }


    public void setBriefing(Boolean briefing)
    {
        this.briefing = briefing;
    }


    public DseObjectTypeAdminMinDto id(Integer id)
    {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getId()
    {
        return id;
    }


    public void setId(Integer id)
    {
        this.id = id;
    }


    public DseObjectTypeAdminMinDto displayName(String displayName)
    {

        this.displayName = displayName;
        return this;
    }

    /**
     * Get displayName
     *
     * @return displayName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDisplayName()
    {
        return displayName;
    }


    public void setDisplayName(String displayName)
    {
        this.displayName = displayName;
    }


    public DseObjectTypeAdminMinDto description(String description)
    {

        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDescription()
    {
        return description;
    }


    public void setDescription(String description)
    {
        this.description = description;
    }


    @Override
    public boolean equals(java.lang.Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DseObjectTypeAdminMinDto dseObjectTypeAdminMinDto = (DseObjectTypeAdminMinDto) o;
        return Objects.equals(this.briefing, dseObjectTypeAdminMinDto.briefing) &&
                Objects.equals(this.id, dseObjectTypeAdminMinDto.id) &&
                Objects.equals(this.displayName, dseObjectTypeAdminMinDto.displayName) &&
                Objects.equals(this.description, dseObjectTypeAdminMinDto.description);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(briefing, id, displayName, description);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DseObjectTypeAdminMinDto {\n");
        sb.append("    briefing: ").append(toIndentedString(briefing)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

