/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Identifier of DSE objects
 */
@ApiModel(description = "Identifier of DSE objects")

public class DseObjectIdentityDto
{
    public static final String SERIALIZED_NAME_INSTANCE_ID = "instanceId";
    @SerializedName(SERIALIZED_NAME_INSTANCE_ID)
    private Integer instanceId;

    public static final String SERIALIZED_NAME_L10N_LOCALE_ID = "l10nLocaleId";
    @SerializedName(SERIALIZED_NAME_L10N_LOCALE_ID)
    private Integer l10nLocaleId;


    public DseObjectIdentityDto instanceId(Integer instanceId)
    {

        this.instanceId = instanceId;
        return this;
    }

    /**
     * @return instanceId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getInstanceId()
    {
        return instanceId;
    }


    public void setInstanceId(Integer instanceId)
    {
        this.instanceId = instanceId;
    }


    public DseObjectIdentityDto l10nLocaleId(Integer l10nLocaleId)
    {

        this.l10nLocaleId = l10nLocaleId;
        return this;
    }

    /**
     * @return l10nLocaleId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getL10nLocaleId()
    {
        return l10nLocaleId;
    }


    public void setL10nLocaleId(Integer l10nLocaleId)
    {
        this.l10nLocaleId = l10nLocaleId;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DseObjectIdentityDto dseObjectIdentityDto = (DseObjectIdentityDto) o;
        return Objects.equals(this.instanceId, dseObjectIdentityDto.instanceId) &&
                Objects.equals(this.l10nLocaleId, dseObjectIdentityDto.l10nLocaleId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(instanceId, l10nLocaleId);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DseObjectIdentityDto {\n");
        sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
        sb.append("    l10nLocaleId: ").append(toIndentedString(l10nLocaleId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

