/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")

public class DseSubObjectTypeAutoCreateRuleDto
{
  public static final String SERIALIZED_NAME_ADDITIONAL_ASSIGNEES = "additionalAssignees";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_ASSIGNEES)
  private List<DseAssigneeMinDto> additionalAssignees = null;

  public static final String SERIALIZED_NAME_ASSIGNEE_ID = "assigneeId";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE_ID)
  private Integer assigneeId;

  public static final String SERIALIZED_NAME_ASSIGNEE_NAME = "assigneeName";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE_NAME)
  private String assigneeName;

  public static final String SERIALIZED_NAME_OBJECT_TYPE_ID = "objectTypeId";
  @SerializedName(SERIALIZED_NAME_OBJECT_TYPE_ID)
  private Integer objectTypeId;

  public static final String SERIALIZED_NAME_OBJECT_TYPE_NAME = "objectTypeName";
  @SerializedName(SERIALIZED_NAME_OBJECT_TYPE_NAME)
  private String objectTypeName;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_OBJECT_NAME = "objectName";
  @SerializedName(SERIALIZED_NAME_OBJECT_NAME)
  private String objectName;

  public static final String SERIALIZED_NAME_OPTIONAL = "optional";
  @SerializedName(SERIALIZED_NAME_OPTIONAL)
  private Boolean optional;

  public static final String SERIALIZED_NAME_OBJECT_WORKFLOW_TYPE_NAME = "objectWorkflowTypeName";
  @SerializedName(SERIALIZED_NAME_OBJECT_WORKFLOW_TYPE_NAME)
  private String objectWorkflowTypeName;

  public static final String SERIALIZED_NAME_OBJECT_WORKFLOW_TYPE_ID = "objectWorkflowTypeId";
  @SerializedName(SERIALIZED_NAME_OBJECT_WORKFLOW_TYPE_ID)
  private Integer objectWorkflowTypeId;

  public static final String SERIALIZED_NAME_PARENT_OBJECT_TYPE_ID = "parentObjectTypeId";
  @SerializedName(SERIALIZED_NAME_PARENT_OBJECT_TYPE_ID)
  private Integer parentObjectTypeId;


  public DseSubObjectTypeAutoCreateRuleDto additionalAssignees(List<DseAssigneeMinDto> additionalAssignees)
  {

    this.additionalAssignees = additionalAssignees;
    return this;
  }

  public DseSubObjectTypeAutoCreateRuleDto addAdditionalAssigneesItem(DseAssigneeMinDto additionalAssigneesItem)
  {
    if (this.additionalAssignees == null)
    {
      this.additionalAssignees = new ArrayList<DseAssigneeMinDto>();
    }
    this.additionalAssignees.add(additionalAssigneesItem);
    return this;
  }

  /**
   * @return additionalAssignees
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DseAssigneeMinDto> getAdditionalAssignees()
  {
    return additionalAssignees;
  }


  public void setAdditionalAssignees(List<DseAssigneeMinDto> additionalAssignees)
  {
    this.additionalAssignees = additionalAssignees;
  }


  public DseSubObjectTypeAutoCreateRuleDto assigneeId(Integer assigneeId)
  {

    this.assigneeId = assigneeId;
    return this;
  }

  /**
   * @return assigneeId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAssigneeId()
  {
    return assigneeId;
  }


  public void setAssigneeId(Integer assigneeId)
  {
    this.assigneeId = assigneeId;
  }


  public DseSubObjectTypeAutoCreateRuleDto assigneeName(String assigneeName)
  {

    this.assigneeName = assigneeName;
    return this;
  }

  /**
   * @return assigneeName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAssigneeName()
  {
    return assigneeName;
  }


  public void setAssigneeName(String assigneeName)
  {
    this.assigneeName = assigneeName;
  }


  public DseSubObjectTypeAutoCreateRuleDto objectTypeId(Integer objectTypeId)
  {

    this.objectTypeId = objectTypeId;
    return this;
  }

  /**
   * @return objectTypeId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getObjectTypeId()
  {
    return objectTypeId;
  }


  public void setObjectTypeId(Integer objectTypeId)
  {
    this.objectTypeId = objectTypeId;
  }


  public DseSubObjectTypeAutoCreateRuleDto objectTypeName(String objectTypeName)
  {

    this.objectTypeName = objectTypeName;
    return this;
  }

  /**
   * @return objectTypeName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getObjectTypeName()
  {
    return objectTypeName;
  }


  public void setObjectTypeName(String objectTypeName)
  {
    this.objectTypeName = objectTypeName;
  }


  public DseSubObjectTypeAutoCreateRuleDto id(Integer id)
  {

    this.id = id;
    return this;
  }

  /**
   * @return id
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId()
  {
    return id;
  }


  public void setId(Integer id)
  {
    this.id = id;
  }


  public DseSubObjectTypeAutoCreateRuleDto objectName(String objectName)
  {

    this.objectName = objectName;
    return this;
  }

  /**
   * @return objectName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getObjectName()
  {
    return objectName;
  }


  public void setObjectName(String objectName)
  {
    this.objectName = objectName;
  }


  public DseSubObjectTypeAutoCreateRuleDto optional(Boolean optional)
  {

    this.optional = optional;
    return this;
  }

  /**
   * @return optional
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOptional()
  {
    return optional;
  }


  public void setOptional(Boolean optional)
  {
    this.optional = optional;
  }


  public DseSubObjectTypeAutoCreateRuleDto objectWorkflowTypeName(String objectWorkflowTypeName)
  {

    this.objectWorkflowTypeName = objectWorkflowTypeName;
    return this;
  }

  /**
   * @return objectWorkflowTypeName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getObjectWorkflowTypeName()
  {
    return objectWorkflowTypeName;
  }


  public void setObjectWorkflowTypeName(String objectWorkflowTypeName)
  {
    this.objectWorkflowTypeName = objectWorkflowTypeName;
  }


  public DseSubObjectTypeAutoCreateRuleDto objectWorkflowTypeId(Integer objectWorkflowTypeId)
  {

    this.objectWorkflowTypeId = objectWorkflowTypeId;
    return this;
  }

  /**
   * @return objectWorkflowTypeId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getObjectWorkflowTypeId()
  {
    return objectWorkflowTypeId;
  }


  public void setObjectWorkflowTypeId(Integer objectWorkflowTypeId)
  {
    this.objectWorkflowTypeId = objectWorkflowTypeId;
  }


  public DseSubObjectTypeAutoCreateRuleDto parentObjectTypeId(Integer parentObjectTypeId)
  {

    this.parentObjectTypeId = parentObjectTypeId;
    return this;
  }

  /**
   * @return parentObjectTypeId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getParentObjectTypeId()
  {
    return parentObjectTypeId;
  }


  public void setParentObjectTypeId(Integer parentObjectTypeId)
  {
    this.parentObjectTypeId = parentObjectTypeId;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    DseSubObjectTypeAutoCreateRuleDto dseSubObjectTypeAutoCreateRuleDto = (DseSubObjectTypeAutoCreateRuleDto) o;
    return Objects.equals(this.additionalAssignees, dseSubObjectTypeAutoCreateRuleDto.additionalAssignees) &&
            Objects.equals(this.assigneeId, dseSubObjectTypeAutoCreateRuleDto.assigneeId) &&
            Objects.equals(this.assigneeName, dseSubObjectTypeAutoCreateRuleDto.assigneeName) &&
            Objects.equals(this.objectTypeId, dseSubObjectTypeAutoCreateRuleDto.objectTypeId) &&
            Objects.equals(this.objectTypeName, dseSubObjectTypeAutoCreateRuleDto.objectTypeName) &&
            Objects.equals(this.id, dseSubObjectTypeAutoCreateRuleDto.id) &&
            Objects.equals(this.objectName, dseSubObjectTypeAutoCreateRuleDto.objectName) &&
            Objects.equals(this.optional, dseSubObjectTypeAutoCreateRuleDto.optional) &&
            Objects.equals(this.objectWorkflowTypeName, dseSubObjectTypeAutoCreateRuleDto.objectWorkflowTypeName) &&
            Objects.equals(this.objectWorkflowTypeId, dseSubObjectTypeAutoCreateRuleDto.objectWorkflowTypeId) &&
            Objects.equals(this.parentObjectTypeId, dseSubObjectTypeAutoCreateRuleDto.parentObjectTypeId);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(additionalAssignees, assigneeId, assigneeName, objectTypeId, objectTypeName, id, objectName, optional, objectWorkflowTypeName, objectWorkflowTypeId, parentObjectTypeId);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DseSubObjectTypeAutoCreateRuleDto {\n");
    sb.append("    additionalAssignees: ").append(toIndentedString(additionalAssignees)).append("\n");
    sb.append("    assigneeId: ").append(toIndentedString(assigneeId)).append("\n");
    sb.append("    assigneeName: ").append(toIndentedString(assigneeName)).append("\n");
    sb.append("    objectTypeId: ").append(toIndentedString(objectTypeId)).append("\n");
    sb.append("    objectTypeName: ").append(toIndentedString(objectTypeName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
    sb.append("    objectWorkflowTypeName: ").append(toIndentedString(objectWorkflowTypeName)).append("\n");
    sb.append("    objectWorkflowTypeId: ").append(toIndentedString(objectWorkflowTypeId)).append("\n");
    sb.append("    parentObjectTypeId: ").append(toIndentedString(parentObjectTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

