/*
 * DSE REST API
 * <h2>DSE REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import admin.api.MRM.externalAPI.api.DseObjectTypeAdminRestServiceV1Api;
import admin.api.MRM.externalAPI.api.WorkflowTypeServiceApi;
import com.google.gson.annotations.SerializedName;
import io.restassured.http.Method;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import utils.ExlcudeFromGeneration;
import utils.Mandatory;

import java.util.Objects;

/**
 * Dto for creating job (old dse object)
 */
@ApiModel(description = "Dto for creating job (old dse object)")

public class JobCreateDto
{
    public static final String SERIALIZED_NAME_DSE_OBJECT_TYPE_ID = "dseObjectTypeId";
    @SerializedName(SERIALIZED_NAME_DSE_OBJECT_TYPE_ID)
    @Mandatory(service = DseObjectTypeAdminRestServiceV1Api.DseObjectTypeAdminRestServiceV1GETGetAllDseObjectTypesOper.class, httpMethod = Method.GET, uriPath = "/dse/rest/v1.0/admin/object-types", jsonPath = "find {e -> e.displayName == '@QA_SIMPLE_JOB'}.id")
    private Integer dseObjectTypeId;

    public static final String SERIALIZED_NAME_WORKFLOW_TYPE_ID = "workflowTypeId";
    @SerializedName(SERIALIZED_NAME_WORKFLOW_TYPE_ID)
    @Mandatory(service = WorkflowTypeServiceApi.GetProcessListOper.class, httpMethod = Method.GET, uriPath = "/wf/type", jsonPath = "find {e -> e.name == '@qa 2 steps'}.workflowTypeId")
    private Integer workflowTypeId;

    public static final String SERIALIZED_NAME_PARENT_JOB_ID = "parentJobId";
    @SerializedName(SERIALIZED_NAME_PARENT_JOB_ID)
    @ExlcudeFromGeneration
    private Integer parentJobId;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;


    public JobCreateDto dseObjectTypeId(Integer dseObjectTypeId)
    {

        this.dseObjectTypeId = dseObjectTypeId;
        return this;
    }

    /**
     * Job type id (Required)
     *
     * @return dseObjectTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Job type id (Required)")

    public Integer getDseObjectTypeId()
    {
        return dseObjectTypeId;
    }


    public void setDseObjectTypeId(Integer dseObjectTypeId)
    {
        this.dseObjectTypeId = dseObjectTypeId;
    }


    public JobCreateDto workflowTypeId(Integer workflowTypeId)
    {

        this.workflowTypeId = workflowTypeId;
        return this;
    }

    /**
     * Job type workflow id (Required)
     *
     * @return workflowTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Job type workflow id (Required)")

    public Integer getWorkflowTypeId()
    {
        return workflowTypeId;
    }


    public void setWorkflowTypeId(Integer workflowTypeId)
    {
        this.workflowTypeId = workflowTypeId;
    }


    public JobCreateDto parentJobId(Integer parentJobId)
    {

        this.parentJobId = parentJobId;
        return this;
    }

    /**
     * Parent job id (Optional)
     *
     * @return parentJobId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Parent job id (Optional)")

    public Integer getParentJobId()
    {
        return parentJobId;
    }


    public void setParentJobId(Integer parentJobId)
    {
        this.parentJobId = parentJobId;
    }


    public JobCreateDto name(String name)
    {

        this.name = name;
        return this;
    }

    /**
     * New job name (Required)
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "New job name (Required)")

    public String getName()
    {
        return name;
    }


    public void setName(String name)
    {
        this.name = name;
    }


    @Override
    public boolean equals(java.lang.Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        JobCreateDto jobCreateDto = (JobCreateDto) o;
        return Objects.equals(this.dseObjectTypeId, jobCreateDto.dseObjectTypeId) &&
                Objects.equals(this.workflowTypeId, jobCreateDto.workflowTypeId) &&
                Objects.equals(this.parentJobId, jobCreateDto.parentJobId) &&
                Objects.equals(this.name, jobCreateDto.name);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(dseObjectTypeId, workflowTypeId, parentJobId, name);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobCreateDto {\n");
        sb.append("    dseObjectTypeId: ").append(toIndentedString(dseObjectTypeId)).append("\n");
        sb.append("    workflowTypeId: ").append(toIndentedString(workflowTypeId)).append("\n");
        sb.append("    parentJobId: ").append(toIndentedString(parentJobId)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

