/*
 * DSE REST API
 * <h2>DSE REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DTO for label-value pair.
 */
@ApiModel(description = "DTO for label-value pair.")

public class JobUpdateValueDto
{
    public static final String SERIALIZED_NAME_INHERIT_FROM_PARENT = "inheritFromParent";
    @SerializedName(SERIALIZED_NAME_INHERIT_FROM_PARENT)
    private InheritFromParentEnum inheritFromParent;

    public static final String SERIALIZED_NAME_VALUE = "value";
    @SerializedName(SERIALIZED_NAME_VALUE)
    private String value;

    public static final String SERIALIZED_NAME_TECHNICAL_NAME = "technicalName";
    @SerializedName(SERIALIZED_NAME_TECHNICAL_NAME)
    private String technicalName;


    public JobUpdateValueDto inheritFromParent(InheritFromParentEnum inheritFromParent)
    {

        this.inheritFromParent = inheritFromParent;
        return this;
    }

    /**
     * Get inheritFromParent
     *
     * @return inheritFromParent
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public InheritFromParentEnum getInheritFromParent()
    {
        return inheritFromParent;
    }


    public void setInheritFromParent(InheritFromParentEnum inheritFromParent)
    {
        this.inheritFromParent = inheritFromParent;
    }


    public JobUpdateValueDto value(String value)
    {

        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getValue()
    {
        return value;
    }


    public void setValue(String value)
    {
        this.value = value;
    }


    public JobUpdateValueDto technicalName(String technicalName)
    {

        this.technicalName = technicalName;
        return this;
    }

    /**
     * Get technicalName
     *
     * @return technicalName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getTechnicalName()
    {
        return technicalName;
    }


    public void setTechnicalName(String technicalName)
    {
        this.technicalName = technicalName;
    }


    @Override
    public boolean equals(java.lang.Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        JobUpdateValueDto jobUpdateValueDto = (JobUpdateValueDto) o;
        return Objects.equals(this.inheritFromParent, jobUpdateValueDto.inheritFromParent) &&
                Objects.equals(this.value, jobUpdateValueDto.value) &&
                Objects.equals(this.technicalName, jobUpdateValueDto.technicalName);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(inheritFromParent, value, technicalName);
    }


    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobUpdateValueDto {\n");
        sb.append("    inheritFromParent: ").append(toIndentedString(inheritFromParent)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    technicalName: ").append(toIndentedString(technicalName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

