/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 *
 */
@ApiModel(description = "")

public class MethodDto
{
    public static final String SERIALIZED_NAME_DESCRIPTION = "description";
    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    private String description;

    public static final String SERIALIZED_NAME_PATH = "path";
    @SerializedName(SERIALIZED_NAME_PATH)
    private String path;

    public static final String SERIALIZED_NAME_SUMMARY = "summary";
    @SerializedName(SERIALIZED_NAME_SUMMARY)
    private String summary;

    public static final String SERIALIZED_NAME_HTTP_METHOD = "httpMethod";
    @SerializedName(SERIALIZED_NAME_HTTP_METHOD)
    private HttpMethod httpMethod;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public static final String SERIALIZED_NAME_RESPONSES = "responses";
    @SerializedName(SERIALIZED_NAME_RESPONSES)
    private List<ResponseDto> responses = null;

    public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
    @SerializedName(SERIALIZED_NAME_PARAMETERS)
    private List<ParameterDto> parameters = null;


    public MethodDto description(String description)
    {

        this.description = description;
        return this;
    }

    /**
     * @return description
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDescription()
    {
        return description;
    }


    public void setDescription(String description)
    {
        this.description = description;
    }


    public MethodDto path(String path)
    {

        this.path = path;
        return this;
    }

    /**
     * @return path
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPath()
    {
        return path;
    }


    public void setPath(String path)
    {
        this.path = path;
    }


    public MethodDto summary(String summary)
    {

        this.summary = summary;
        return this;
    }

    /**
     * @return summary
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSummary()
    {
        return summary;
    }


    public void setSummary(String summary)
    {
        this.summary = summary;
    }


    public MethodDto httpMethod(HttpMethod httpMethod)
    {

        this.httpMethod = httpMethod;
        return this;
    }

    /**
     * Get httpMethod
     *
     * @return httpMethod
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public HttpMethod getHttpMethod()
    {
        return httpMethod;
    }


    public void setHttpMethod(HttpMethod httpMethod)
    {
        this.httpMethod = httpMethod;
    }


    public MethodDto name(String name)
    {

        this.name = name;
        return this;
    }

    /**
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getName()
    {
        return name;
    }


    public void setName(String name)
    {
        this.name = name;
    }


    public MethodDto responses(List<ResponseDto> responses)
    {

        this.responses = responses;
        return this;
    }

    public MethodDto addResponsesItem(ResponseDto responsesItem)
    {
        if (this.responses == null)
        {
            this.responses = new ArrayList<ResponseDto>();
        }
        this.responses.add(responsesItem);
        return this;
    }

    /**
     * @return responses
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<ResponseDto> getResponses()
    {
        return responses;
    }


    public void setResponses(List<ResponseDto> responses)
    {
        this.responses = responses;
    }


    public MethodDto parameters(List<ParameterDto> parameters)
    {

        this.parameters = parameters;
        return this;
    }

    public MethodDto addParametersItem(ParameterDto parametersItem)
    {
        if (this.parameters == null)
        {
            this.parameters = new ArrayList<ParameterDto>();
        }
        this.parameters.add(parametersItem);
        return this;
    }

    /**
     * @return parameters
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<ParameterDto> getParameters()
    {
        return parameters;
    }


    public void setParameters(List<ParameterDto> parameters)
    {
        this.parameters = parameters;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        MethodDto methodDto = (MethodDto) o;
        return Objects.equals(this.description, methodDto.description) &&
                Objects.equals(this.path, methodDto.path) &&
                Objects.equals(this.summary, methodDto.summary) &&
                Objects.equals(this.httpMethod, methodDto.httpMethod) &&
                Objects.equals(this.name, methodDto.name) &&
                Objects.equals(this.responses, methodDto.responses) &&
                Objects.equals(this.parameters, methodDto.parameters);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(description, path, summary, httpMethod, name, responses, parameters);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class MethodDto {\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    path: ").append(toIndentedString(path)).append("\n");
        sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
        sb.append("    httpMethod: ").append(toIndentedString(httpMethod)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    responses: ").append(toIndentedString(responses)).append("\n");
        sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

