/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 *
 */
@ApiModel(description = "")

public class ModelData
{
    public static final String SERIALIZED_NAME_XML = "xml";
    @SerializedName(SERIALIZED_NAME_XML)
    private String xml;

    public static final String SERIALIZED_NAME_MODEL = "model";
    @SerializedName(SERIALIZED_NAME_MODEL)
    private Object model;


    public ModelData xml(String xml)
    {

        this.xml = xml;
        return this;
    }

    /**
     * @return xml
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getXml()
    {
        return xml;
    }


    public void setXml(String xml)
    {
        this.xml = xml;
    }


    public ModelData model(Object model)
    {

        this.model = model;
        return this;
    }

    /**
     * @return model
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Object getModel()
    {
        return model;
    }


    public void setModel(Object model)
    {
        this.model = model;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        ModelData modelData = (ModelData) o;
        return Objects.equals(this.xml, modelData.xml) &&
                Objects.equals(this.model, modelData.model);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(xml, model);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ModelData {\n");
        sb.append("    xml: ").append(toIndentedString(xml)).append("\n");
        sb.append("    model: ").append(toIndentedString(model)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

