/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * MultiValueInputLineDtoAllOf
 */

public class MultiValueInputLineDtoAllOf
{
    public static final String SERIALIZED_NAME_TYPE_SPANNING = "typeSpanning";
    @SerializedName(SERIALIZED_NAME_TYPE_SPANNING)
    private Boolean typeSpanning;

    public static final String SERIALIZED_NAME_PERCENTAGE1 = "percentage1";
    @SerializedName(SERIALIZED_NAME_PERCENTAGE1)
    private Integer percentage1;

    public static final String SERIALIZED_NAME_PERCENTAGE2 = "percentage2";
    @SerializedName(SERIALIZED_NAME_PERCENTAGE2)
    private Integer percentage2;

    public static final String SERIALIZED_NAME_MAX_CHARACTER1 = "maxCharacter1";
    @SerializedName(SERIALIZED_NAME_MAX_CHARACTER1)
    private Integer maxCharacter1;

    public static final String SERIALIZED_NAME_MAX_CHARACTER2 = "maxCharacter2";
    @SerializedName(SERIALIZED_NAME_MAX_CHARACTER2)
    private Integer maxCharacter2;

    public static final String SERIALIZED_NAME_REGEXP1 = "regexp1";
    @SerializedName(SERIALIZED_NAME_REGEXP1)
    private String regexp1;

    public static final String SERIALIZED_NAME_REGEXP2 = "regexp2";
    @SerializedName(SERIALIZED_NAME_REGEXP2)
    private String regexp2;

    public static final String SERIALIZED_NAME_INPUT_SIZE1 = "inputSize1";
    @SerializedName(SERIALIZED_NAME_INPUT_SIZE1)
    private Integer inputSize1;

    public static final String SERIALIZED_NAME_INPUT_SIZE2 = "inputSize2";
    @SerializedName(SERIALIZED_NAME_INPUT_SIZE2)
    private Integer inputSize2;

    public static final String SERIALIZED_NAME_SUFFIX1 = "suffix1";
    @SerializedName(SERIALIZED_NAME_SUFFIX1)
    private String suffix1;

    public static final String SERIALIZED_NAME_SUFFIX2 = "suffix2";
    @SerializedName(SERIALIZED_NAME_SUFFIX2)
    private String suffix2;

    public static final String SERIALIZED_NAME_DEFAULT_VALUE1 = "defaultValue1";
    @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE1)
    private String defaultValue1;

    public static final String SERIALIZED_NAME_DEFAULT_VALUE2 = "defaultValue2";
    @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE2)
    private String defaultValue2;

    public static final String SERIALIZED_NAME_COLUMN1_UNIQUE_NAME = "column1UniqueName";
    @SerializedName(SERIALIZED_NAME_COLUMN1_UNIQUE_NAME)
    private String column1UniqueName;

    public static final String SERIALIZED_NAME_COLUMN2_UNIQUE_NAME = "column2UniqueName";
    @SerializedName(SERIALIZED_NAME_COLUMN2_UNIQUE_NAME)
    private String column2UniqueName;


    public MultiValueInputLineDtoAllOf typeSpanning(Boolean typeSpanning)
    {

        this.typeSpanning = typeSpanning;
        return this;
    }

    /**
     * @return typeSpanning
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getTypeSpanning()
    {
        return typeSpanning;
    }


    public void setTypeSpanning(Boolean typeSpanning)
    {
        this.typeSpanning = typeSpanning;
    }


    public MultiValueInputLineDtoAllOf percentage1(Integer percentage1)
    {

        this.percentage1 = percentage1;
        return this;
    }

    /**
     * @return percentage1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getPercentage1()
    {
        return percentage1;
    }


    public void setPercentage1(Integer percentage1)
    {
        this.percentage1 = percentage1;
    }


    public MultiValueInputLineDtoAllOf percentage2(Integer percentage2)
    {

        this.percentage2 = percentage2;
        return this;
    }

    /**
     * @return percentage2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getPercentage2()
    {
        return percentage2;
    }


    public void setPercentage2(Integer percentage2)
    {
        this.percentage2 = percentage2;
    }


    public MultiValueInputLineDtoAllOf maxCharacter1(Integer maxCharacter1)
    {

        this.maxCharacter1 = maxCharacter1;
        return this;
    }

    /**
     * @return maxCharacter1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMaxCharacter1()
    {
        return maxCharacter1;
    }


    public void setMaxCharacter1(Integer maxCharacter1)
    {
        this.maxCharacter1 = maxCharacter1;
    }


    public MultiValueInputLineDtoAllOf maxCharacter2(Integer maxCharacter2)
    {

        this.maxCharacter2 = maxCharacter2;
        return this;
    }

    /**
     * @return maxCharacter2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMaxCharacter2()
    {
        return maxCharacter2;
    }


    public void setMaxCharacter2(Integer maxCharacter2)
    {
        this.maxCharacter2 = maxCharacter2;
    }


    public MultiValueInputLineDtoAllOf regexp1(String regexp1)
    {

        this.regexp1 = regexp1;
        return this;
    }

    /**
     * @return regexp1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getRegexp1()
    {
        return regexp1;
    }


    public void setRegexp1(String regexp1)
    {
        this.regexp1 = regexp1;
    }


    public MultiValueInputLineDtoAllOf regexp2(String regexp2)
    {

        this.regexp2 = regexp2;
        return this;
    }

    /**
     * @return regexp2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getRegexp2()
    {
        return regexp2;
    }


    public void setRegexp2(String regexp2)
    {
        this.regexp2 = regexp2;
    }


    public MultiValueInputLineDtoAllOf inputSize1(Integer inputSize1)
    {

        this.inputSize1 = inputSize1;
        return this;
    }

    /**
     * @return inputSize1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getInputSize1()
    {
        return inputSize1;
    }


    public void setInputSize1(Integer inputSize1)
    {
        this.inputSize1 = inputSize1;
    }


    public MultiValueInputLineDtoAllOf inputSize2(Integer inputSize2)
    {

        this.inputSize2 = inputSize2;
        return this;
    }

    /**
     * @return inputSize2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getInputSize2()
    {
        return inputSize2;
    }


    public void setInputSize2(Integer inputSize2)
    {
        this.inputSize2 = inputSize2;
    }


    public MultiValueInputLineDtoAllOf suffix1(String suffix1)
    {

        this.suffix1 = suffix1;
        return this;
    }

    /**
     * @return suffix1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSuffix1()
    {
        return suffix1;
    }


    public void setSuffix1(String suffix1)
    {
        this.suffix1 = suffix1;
    }


    public MultiValueInputLineDtoAllOf suffix2(String suffix2)
    {

        this.suffix2 = suffix2;
        return this;
    }

    /**
     * @return suffix2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSuffix2()
    {
        return suffix2;
    }


    public void setSuffix2(String suffix2)
    {
        this.suffix2 = suffix2;
    }


    public MultiValueInputLineDtoAllOf defaultValue1(String defaultValue1)
    {

        this.defaultValue1 = defaultValue1;
        return this;
    }

    /**
     * @return defaultValue1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDefaultValue1()
    {
        return defaultValue1;
    }


    public void setDefaultValue1(String defaultValue1)
    {
        this.defaultValue1 = defaultValue1;
    }


    public MultiValueInputLineDtoAllOf defaultValue2(String defaultValue2)
    {

        this.defaultValue2 = defaultValue2;
        return this;
    }

    /**
     * @return defaultValue2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDefaultValue2()
    {
        return defaultValue2;
    }


    public void setDefaultValue2(String defaultValue2)
    {
        this.defaultValue2 = defaultValue2;
    }


    public MultiValueInputLineDtoAllOf column1UniqueName(String column1UniqueName)
    {

        this.column1UniqueName = column1UniqueName;
        return this;
    }

    /**
     * @return column1UniqueName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getColumn1UniqueName()
    {
        return column1UniqueName;
    }


    public void setColumn1UniqueName(String column1UniqueName)
    {
        this.column1UniqueName = column1UniqueName;
    }


    public MultiValueInputLineDtoAllOf column2UniqueName(String column2UniqueName)
    {

        this.column2UniqueName = column2UniqueName;
        return this;
    }

    /**
     * @return column2UniqueName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getColumn2UniqueName()
    {
        return column2UniqueName;
    }


    public void setColumn2UniqueName(String column2UniqueName)
    {
        this.column2UniqueName = column2UniqueName;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        MultiValueInputLineDtoAllOf multiValueInputLineDtoAllOf = (MultiValueInputLineDtoAllOf) o;
        return Objects.equals(this.typeSpanning, multiValueInputLineDtoAllOf.typeSpanning) &&
                Objects.equals(this.percentage1, multiValueInputLineDtoAllOf.percentage1) &&
                Objects.equals(this.percentage2, multiValueInputLineDtoAllOf.percentage2) &&
                Objects.equals(this.maxCharacter1, multiValueInputLineDtoAllOf.maxCharacter1) &&
                Objects.equals(this.maxCharacter2, multiValueInputLineDtoAllOf.maxCharacter2) &&
                Objects.equals(this.regexp1, multiValueInputLineDtoAllOf.regexp1) &&
                Objects.equals(this.regexp2, multiValueInputLineDtoAllOf.regexp2) &&
                Objects.equals(this.inputSize1, multiValueInputLineDtoAllOf.inputSize1) &&
                Objects.equals(this.inputSize2, multiValueInputLineDtoAllOf.inputSize2) &&
                Objects.equals(this.suffix1, multiValueInputLineDtoAllOf.suffix1) &&
                Objects.equals(this.suffix2, multiValueInputLineDtoAllOf.suffix2) &&
                Objects.equals(this.defaultValue1, multiValueInputLineDtoAllOf.defaultValue1) &&
                Objects.equals(this.defaultValue2, multiValueInputLineDtoAllOf.defaultValue2) &&
                Objects.equals(this.column1UniqueName, multiValueInputLineDtoAllOf.column1UniqueName) &&
                Objects.equals(this.column2UniqueName, multiValueInputLineDtoAllOf.column2UniqueName);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(typeSpanning, percentage1, percentage2, maxCharacter1, maxCharacter2, regexp1, regexp2, inputSize1, inputSize2, suffix1, suffix2, defaultValue1, defaultValue2, column1UniqueName, column2UniqueName);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class MultiValueInputLineDtoAllOf {\n");
        sb.append("    typeSpanning: ").append(toIndentedString(typeSpanning)).append("\n");
        sb.append("    percentage1: ").append(toIndentedString(percentage1)).append("\n");
        sb.append("    percentage2: ").append(toIndentedString(percentage2)).append("\n");
        sb.append("    maxCharacter1: ").append(toIndentedString(maxCharacter1)).append("\n");
        sb.append("    maxCharacter2: ").append(toIndentedString(maxCharacter2)).append("\n");
        sb.append("    regexp1: ").append(toIndentedString(regexp1)).append("\n");
        sb.append("    regexp2: ").append(toIndentedString(regexp2)).append("\n");
        sb.append("    inputSize1: ").append(toIndentedString(inputSize1)).append("\n");
        sb.append("    inputSize2: ").append(toIndentedString(inputSize2)).append("\n");
        sb.append("    suffix1: ").append(toIndentedString(suffix1)).append("\n");
        sb.append("    suffix2: ").append(toIndentedString(suffix2)).append("\n");
        sb.append("    defaultValue1: ").append(toIndentedString(defaultValue1)).append("\n");
        sb.append("    defaultValue2: ").append(toIndentedString(defaultValue2)).append("\n");
        sb.append("    column1UniqueName: ").append(toIndentedString(column1UniqueName)).append("\n");
        sb.append("    column2UniqueName: ").append(toIndentedString(column2UniqueName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

