/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * NoDimensionValueExceptionAllOf
 */

public class NoDimensionValueExceptionAllOf
{
    public static final String SERIALIZED_NAME_PROPOSED_VALUE = "proposedValue";
    @SerializedName(SERIALIZED_NAME_PROPOSED_VALUE)
    private MaplDimensionValueViewBase proposedValue;

    public static final String SERIALIZED_NAME_POSSIBLE_VALUES = "possibleValues";
    @SerializedName(SERIALIZED_NAME_POSSIBLE_VALUES)
    private List<MaplDimensionPossibleValueDto> possibleValues = null;


    public NoDimensionValueExceptionAllOf proposedValue(MaplDimensionValueViewBase proposedValue)
    {

        this.proposedValue = proposedValue;
        return this;
    }

    /**
     * Get proposedValue
     *
     * @return proposedValue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public MaplDimensionValueViewBase getProposedValue()
    {
        return proposedValue;
    }


    public void setProposedValue(MaplDimensionValueViewBase proposedValue)
    {
        this.proposedValue = proposedValue;
    }


    public NoDimensionValueExceptionAllOf possibleValues(List<MaplDimensionPossibleValueDto> possibleValues)
    {

        this.possibleValues = possibleValues;
        return this;
    }

    public NoDimensionValueExceptionAllOf addPossibleValuesItem(MaplDimensionPossibleValueDto possibleValuesItem)
    {
        if (this.possibleValues == null)
        {
            this.possibleValues = new ArrayList<MaplDimensionPossibleValueDto>();
        }
        this.possibleValues.add(possibleValuesItem);
        return this;
    }

    /**
     * @return possibleValues
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<MaplDimensionPossibleValueDto> getPossibleValues()
    {
        return possibleValues;
    }


    public void setPossibleValues(List<MaplDimensionPossibleValueDto> possibleValues)
    {
        this.possibleValues = possibleValues;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        NoDimensionValueExceptionAllOf noDimensionValueExceptionAllOf = (NoDimensionValueExceptionAllOf) o;
        return Objects.equals(this.proposedValue, noDimensionValueExceptionAllOf.proposedValue) &&
                Objects.equals(this.possibleValues, noDimensionValueExceptionAllOf.possibleValues);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(proposedValue, possibleValues);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class NoDimensionValueExceptionAllOf {\n");
        sb.append("    proposedValue: ").append(toIndentedString(proposedValue)).append("\n");
        sb.append("    possibleValues: ").append(toIndentedString(possibleValues)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

