/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * OldWorkflowTypeAllOf
 */

public class OldWorkflowTypeAllOf
{
  public static final String SERIALIZED_NAME_REUSABLE = "reusable";
  @SerializedName(SERIALIZED_NAME_REUSABLE)
  private Boolean reusable;

  public static final String SERIALIZED_NAME_REUSABLE_UPDATE_DATE = "reusableUpdateDate";
  @SerializedName(SERIALIZED_NAME_REUSABLE_UPDATE_DATE)
  private Integer reusableUpdateDate;

  public static final String SERIALIZED_NAME_REAPPROVAL_REQUIRED = "reapprovalRequired";
  @SerializedName(SERIALIZED_NAME_REAPPROVAL_REQUIRED)
  private Integer reapprovalRequired;


  public OldWorkflowTypeAllOf reusable(Boolean reusable)
  {

    this.reusable = reusable;
    return this;
  }

  /**
   * @return reusable
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getReusable()
  {
    return reusable;
  }


  public void setReusable(Boolean reusable)
  {
    this.reusable = reusable;
  }


  public OldWorkflowTypeAllOf reusableUpdateDate(Integer reusableUpdateDate)
  {

    this.reusableUpdateDate = reusableUpdateDate;
    return this;
  }

  /**
   * @return reusableUpdateDate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReusableUpdateDate()
  {
    return reusableUpdateDate;
  }


  public void setReusableUpdateDate(Integer reusableUpdateDate)
  {
    this.reusableUpdateDate = reusableUpdateDate;
  }


  public OldWorkflowTypeAllOf reapprovalRequired(Integer reapprovalRequired)
  {

    this.reapprovalRequired = reapprovalRequired;
    return this;
  }

  /**
   * @return reapprovalRequired
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReapprovalRequired()
  {
    return reapprovalRequired;
  }


  public void setReapprovalRequired(Integer reapprovalRequired)
  {
    this.reapprovalRequired = reapprovalRequired;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    OldWorkflowTypeAllOf oldWorkflowTypeAllOf = (OldWorkflowTypeAllOf) o;
    return Objects.equals(this.reusable, oldWorkflowTypeAllOf.reusable) &&
            Objects.equals(this.reusableUpdateDate, oldWorkflowTypeAllOf.reusableUpdateDate) &&
            Objects.equals(this.reapprovalRequired, oldWorkflowTypeAllOf.reapprovalRequired);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(reusable, reusableUpdateDate, reapprovalRequired);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OldWorkflowTypeAllOf {\n");
    sb.append("    reusable: ").append(toIndentedString(reusable)).append("\n");
    sb.append("    reusableUpdateDate: ").append(toIndentedString(reusableUpdateDate)).append("\n");
    sb.append("    reapprovalRequired: ").append(toIndentedString(reapprovalRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

