/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")

public class PagingWrapperDtoOfProductIdsDto
{
  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<ProductIdsDto> items = null;


  public PagingWrapperDtoOfProductIdsDto total(Integer total)
  {

    this.total = total;
    return this;
  }

  /**
   * @return total
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotal()
  {
    return total;
  }


  public void setTotal(Integer total)
  {
    this.total = total;
  }


  public PagingWrapperDtoOfProductIdsDto items(List<ProductIdsDto> items)
  {

    this.items = items;
    return this;
  }

  public PagingWrapperDtoOfProductIdsDto addItemsItem(ProductIdsDto itemsItem)
  {
    if (this.items == null)
    {
      this.items = new ArrayList<ProductIdsDto>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * @return items
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ProductIdsDto> getItems()
  {
    return items;
  }


  public void setItems(List<ProductIdsDto> items)
  {
    this.items = items;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    PagingWrapperDtoOfProductIdsDto pagingWrapperDtoOfProductIdsDto = (PagingWrapperDtoOfProductIdsDto) o;
    return Objects.equals(this.total, pagingWrapperDtoOfProductIdsDto.total) &&
            Objects.equals(this.items, pagingWrapperDtoOfProductIdsDto.items);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(total, items);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagingWrapperDtoOfProductIdsDto {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

