/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * RealNumberVariableAllOf
 */

public class RealNumberVariableAllOf
{
  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;


  public RealNumberVariableAllOf unit(String unit)
  {

    this.unit = unit;
    return this;
  }

  /**
   * @return unit
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUnit()
  {
    return unit;
  }


  public void setUnit(String unit)
  {
    this.unit = unit;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    RealNumberVariableAllOf realNumberVariableAllOf = (RealNumberVariableAllOf) o;
    return Objects.equals(this.unit, realNumberVariableAllOf.unit);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(unit);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RealNumberVariableAllOf {\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

