/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Base DTO for variable.
 */
@ApiModel(description = "Base DTO for variable.")

public class RealNumberDto
{
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_META_TYPE_ID = "metaTypeId";
  @SerializedName(SERIALIZED_NAME_META_TYPE_ID)
  private Integer metaTypeId;

  public static final String SERIALIZED_NAME_META_TYPE_NAME = "metaTypeName";
  @SerializedName(SERIALIZED_NAME_META_TYPE_NAME)
  private String metaTypeName;

  public static final String SERIALIZED_NAME_UNIQUE_NAME = "uniqueName";
  @SerializedName(SERIALIZED_NAME_UNIQUE_NAME)
  private String uniqueName;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_RAW_LABEL = "rawLabel";
  @SerializedName(SERIALIZED_NAME_RAW_LABEL)
  private String rawLabel;

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private Integer mode;

  public static final String SERIALIZED_NAME_TECHNICAL_NAME = "technicalName";
  @SerializedName(SERIALIZED_NAME_TECHNICAL_NAME)
  private String technicalName;

  public static final String SERIALIZED_NAME_SHARED_LOCALE = "sharedLocale";
  @SerializedName(SERIALIZED_NAME_SHARED_LOCALE)
  private Boolean sharedLocale;

  public static final String SERIALIZED_NAME_HELP_TEXT = "helpText";
  @SerializedName(SERIALIZED_NAME_HELP_TEXT)
  private String helpText;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private VisibilityDto visibility;

  public static final String SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_ID = "dependsFromVariableId";
  @SerializedName(SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_ID)
  private Integer dependsFromVariableId;

  public static final String SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_VALUES = "dependsFromVariableValues";
  @SerializedName(SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_VALUES)
  private List<String> dependsFromVariableValues = null;

  public static final String SERIALIZED_NAME_TYPE_SPANNING = "typeSpanning";
  @SerializedName(SERIALIZED_NAME_TYPE_SPANNING)
  private Boolean typeSpanning;

  public static final String SERIALIZED_NAME_SYSTEM = "system";
  @SerializedName(SERIALIZED_NAME_SYSTEM)
  private Boolean system;

  public static final String SERIALIZED_NAME_STORAGE_TYPE = "storageType";
  @SerializedName(SERIALIZED_NAME_STORAGE_TYPE)
  private Integer storageType;

  public static final String SERIALIZED_NAME_INHERIT_FROM_PARENT = "inheritFromParent";
  @SerializedName(SERIALIZED_NAME_INHERIT_FROM_PARENT)
  private Boolean inheritFromParent;

  public static final String SERIALIZED_NAME_USES_UNITS = "usesUnits";
  @SerializedName(SERIALIZED_NAME_USES_UNITS)
  private Boolean usesUnits;

  public static final String SERIALIZED_NAME_STORE_UNIT = "storeUnit";
  @SerializedName(SERIALIZED_NAME_STORE_UNIT)
  private String storeUnit;

  public static final String SERIALIZED_NAME_FAMILY = "family";
  @SerializedName(SERIALIZED_NAME_FAMILY)
  private String family;

  public static final String SERIALIZED_NAME_MIN_VALUE = "minValue";
  @SerializedName(SERIALIZED_NAME_MIN_VALUE)
  private BigDecimal minValue;

  public static final String SERIALIZED_NAME_MAX_VALUE = "maxValue";
  @SerializedName(SERIALIZED_NAME_MAX_VALUE)
  private BigDecimal maxValue;

  public static final String SERIALIZED_NAME_DECIMAL_POINT = "decimalPoint";
  @SerializedName(SERIALIZED_NAME_DECIMAL_POINT)
  private String decimalPoint;


  public RealNumberDto id(Integer id)
  {

    this.id = id;
    return this;
  }

  /**
   * @return id
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId()
  {
    return id;
  }


  public void setId(Integer id)
  {
    this.id = id;
  }


  public RealNumberDto metaTypeId(Integer metaTypeId)
  {

    this.metaTypeId = metaTypeId;
    return this;
  }

  /**
   * @return metaTypeId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMetaTypeId()
  {
    return metaTypeId;
  }


  public void setMetaTypeId(Integer metaTypeId)
  {
    this.metaTypeId = metaTypeId;
  }


  public RealNumberDto metaTypeName(String metaTypeName)
  {

    this.metaTypeName = metaTypeName;
    return this;
  }

  /**
   * @return metaTypeName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMetaTypeName()
  {
    return metaTypeName;
  }


  public void setMetaTypeName(String metaTypeName)
  {
    this.metaTypeName = metaTypeName;
  }


  public RealNumberDto uniqueName(String uniqueName)
  {

    this.uniqueName = uniqueName;
    return this;
  }

  /**
   * @return uniqueName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUniqueName()
  {
    return uniqueName;
  }


  public void setUniqueName(String uniqueName)
  {
    this.uniqueName = uniqueName;
  }


  public RealNumberDto displayName(String displayName)
  {

    this.displayName = displayName;
    return this;
  }

  /**
   * @return displayName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDisplayName()
  {
    return displayName;
  }


  public void setDisplayName(String displayName)
  {
    this.displayName = displayName;
  }


  public RealNumberDto rawLabel(String rawLabel)
  {

    this.rawLabel = rawLabel;
    return this;
  }

  /**
   * @return rawLabel
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRawLabel()
  {
    return rawLabel;
  }


  public void setRawLabel(String rawLabel)
  {
    this.rawLabel = rawLabel;
  }


  public RealNumberDto mode(Integer mode)
  {

    this.mode = mode;
    return this;
  }

  /**
   * @return mode
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMode()
  {
    return mode;
  }


  public void setMode(Integer mode)
  {
    this.mode = mode;
  }


  public RealNumberDto technicalName(String technicalName)
  {

    this.technicalName = technicalName;
    return this;
  }

  /**
   * @return technicalName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTechnicalName()
  {
    return technicalName;
  }


  public void setTechnicalName(String technicalName)
  {
    this.technicalName = technicalName;
  }


  public RealNumberDto sharedLocale(Boolean sharedLocale)
  {

    this.sharedLocale = sharedLocale;
    return this;
  }

  /**
   * @return sharedLocale
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSharedLocale()
  {
    return sharedLocale;
  }


  public void setSharedLocale(Boolean sharedLocale)
  {
    this.sharedLocale = sharedLocale;
  }


  public RealNumberDto helpText(String helpText)
  {

    this.helpText = helpText;
    return this;
  }

  /**
   * @return helpText
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHelpText()
  {
    return helpText;
  }


  public void setHelpText(String helpText)
  {
    this.helpText = helpText;
  }


  public RealNumberDto visibility(VisibilityDto visibility)
  {

    this.visibility = visibility;
    return this;
  }

  /**
   * Get visibility
   *
   * @return visibility
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VisibilityDto getVisibility()
  {
    return visibility;
  }


  public void setVisibility(VisibilityDto visibility)
  {
    this.visibility = visibility;
  }


  public RealNumberDto dependsFromVariableId(Integer dependsFromVariableId)
  {

    this.dependsFromVariableId = dependsFromVariableId;
    return this;
  }

  /**
   * @return dependsFromVariableId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDependsFromVariableId()
  {
    return dependsFromVariableId;
  }


  public void setDependsFromVariableId(Integer dependsFromVariableId)
  {
    this.dependsFromVariableId = dependsFromVariableId;
  }


  public RealNumberDto dependsFromVariableValues(List<String> dependsFromVariableValues)
  {

    this.dependsFromVariableValues = dependsFromVariableValues;
    return this;
  }

  public RealNumberDto addDependsFromVariableValuesItem(String dependsFromVariableValuesItem)
  {
    if (this.dependsFromVariableValues == null)
    {
      this.dependsFromVariableValues = new ArrayList<String>();
    }
    this.dependsFromVariableValues.add(dependsFromVariableValuesItem);
    return this;
  }

  /**
   * @return dependsFromVariableValues
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDependsFromVariableValues()
  {
    return dependsFromVariableValues;
  }


  public void setDependsFromVariableValues(List<String> dependsFromVariableValues)
  {
    this.dependsFromVariableValues = dependsFromVariableValues;
  }


  public RealNumberDto typeSpanning(Boolean typeSpanning)
  {

    this.typeSpanning = typeSpanning;
    return this;
  }

  /**
   * @return typeSpanning
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTypeSpanning()
  {
    return typeSpanning;
  }


  public void setTypeSpanning(Boolean typeSpanning)
  {
    this.typeSpanning = typeSpanning;
  }


  public RealNumberDto system(Boolean system)
  {

    this.system = system;
    return this;
  }

  /**
   * @return system
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSystem()
  {
    return system;
  }


  public void setSystem(Boolean system)
  {
    this.system = system;
  }


  public RealNumberDto storageType(Integer storageType)
  {

    this.storageType = storageType;
    return this;
  }

  /**
   * @return storageType
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getStorageType()
  {
    return storageType;
  }


  public void setStorageType(Integer storageType)
  {
    this.storageType = storageType;
  }


  public RealNumberDto inheritFromParent(Boolean inheritFromParent)
  {

    this.inheritFromParent = inheritFromParent;
    return this;
  }

  /**
   * @return inheritFromParent
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getInheritFromParent()
  {
    return inheritFromParent;
  }


  public void setInheritFromParent(Boolean inheritFromParent)
  {
    this.inheritFromParent = inheritFromParent;
  }


  public RealNumberDto usesUnits(Boolean usesUnits)
  {

    this.usesUnits = usesUnits;
    return this;
  }

  /**
   * @return usesUnits
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getUsesUnits()
  {
    return usesUnits;
  }


  public void setUsesUnits(Boolean usesUnits)
  {
    this.usesUnits = usesUnits;
  }


  public RealNumberDto storeUnit(String storeUnit)
  {

    this.storeUnit = storeUnit;
    return this;
  }

  /**
   * @return storeUnit
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStoreUnit()
  {
    return storeUnit;
  }


  public void setStoreUnit(String storeUnit)
  {
    this.storeUnit = storeUnit;
  }


  public RealNumberDto family(String family)
  {

    this.family = family;
    return this;
  }

  /**
   * @return family
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFamily()
  {
    return family;
  }


  public void setFamily(String family)
  {
    this.family = family;
  }


  public RealNumberDto minValue(BigDecimal minValue)
  {

    this.minValue = minValue;
    return this;
  }

  /**
   * @return minValue
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getMinValue()
  {
    return minValue;
  }


  public void setMinValue(BigDecimal minValue)
  {
    this.minValue = minValue;
  }


  public RealNumberDto maxValue(BigDecimal maxValue)
  {

    this.maxValue = maxValue;
    return this;
  }

  /**
   * @return maxValue
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getMaxValue()
  {
    return maxValue;
  }


  public void setMaxValue(BigDecimal maxValue)
  {
    this.maxValue = maxValue;
  }


  public RealNumberDto decimalPoint(String decimalPoint)
  {

    this.decimalPoint = decimalPoint;
    return this;
  }

  /**
   * @return decimalPoint
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDecimalPoint()
  {
    return decimalPoint;
  }


  public void setDecimalPoint(String decimalPoint)
  {
    this.decimalPoint = decimalPoint;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    RealNumberDto realNumberDto = (RealNumberDto) o;
    return Objects.equals(this.id, realNumberDto.id) &&
            Objects.equals(this.metaTypeId, realNumberDto.metaTypeId) &&
            Objects.equals(this.metaTypeName, realNumberDto.metaTypeName) &&
            Objects.equals(this.uniqueName, realNumberDto.uniqueName) &&
            Objects.equals(this.displayName, realNumberDto.displayName) &&
            Objects.equals(this.rawLabel, realNumberDto.rawLabel) &&
            Objects.equals(this.mode, realNumberDto.mode) &&
            Objects.equals(this.technicalName, realNumberDto.technicalName) &&
            Objects.equals(this.sharedLocale, realNumberDto.sharedLocale) &&
            Objects.equals(this.helpText, realNumberDto.helpText) &&
            Objects.equals(this.visibility, realNumberDto.visibility) &&
            Objects.equals(this.dependsFromVariableId, realNumberDto.dependsFromVariableId) &&
            Objects.equals(this.dependsFromVariableValues, realNumberDto.dependsFromVariableValues) &&
            Objects.equals(this.typeSpanning, realNumberDto.typeSpanning) &&
            Objects.equals(this.system, realNumberDto.system) &&
            Objects.equals(this.storageType, realNumberDto.storageType) &&
            Objects.equals(this.inheritFromParent, realNumberDto.inheritFromParent) &&
            Objects.equals(this.usesUnits, realNumberDto.usesUnits) &&
            Objects.equals(this.storeUnit, realNumberDto.storeUnit) &&
            Objects.equals(this.family, realNumberDto.family) &&
            Objects.equals(this.minValue, realNumberDto.minValue) &&
            Objects.equals(this.maxValue, realNumberDto.maxValue) &&
            Objects.equals(this.decimalPoint, realNumberDto.decimalPoint);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(id, metaTypeId, metaTypeName, uniqueName, displayName, rawLabel, mode, technicalName, sharedLocale, helpText, visibility, dependsFromVariableId, dependsFromVariableValues, typeSpanning, system, storageType, inheritFromParent, usesUnits, storeUnit, family, minValue, maxValue, decimalPoint);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RealNumberDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    metaTypeId: ").append(toIndentedString(metaTypeId)).append("\n");
    sb.append("    metaTypeName: ").append(toIndentedString(metaTypeName)).append("\n");
    sb.append("    uniqueName: ").append(toIndentedString(uniqueName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    rawLabel: ").append(toIndentedString(rawLabel)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    technicalName: ").append(toIndentedString(technicalName)).append("\n");
    sb.append("    sharedLocale: ").append(toIndentedString(sharedLocale)).append("\n");
    sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    dependsFromVariableId: ").append(toIndentedString(dependsFromVariableId)).append("\n");
    sb.append("    dependsFromVariableValues: ").append(toIndentedString(dependsFromVariableValues)).append("\n");
    sb.append("    typeSpanning: ").append(toIndentedString(typeSpanning)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    storageType: ").append(toIndentedString(storageType)).append("\n");
    sb.append("    inheritFromParent: ").append(toIndentedString(inheritFromParent)).append("\n");
    sb.append("    usesUnits: ").append(toIndentedString(usesUnits)).append("\n");
    sb.append("    storeUnit: ").append(toIndentedString(storeUnit)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    minValue: ").append(toIndentedString(minValue)).append("\n");
    sb.append("    maxValue: ").append(toIndentedString(maxValue)).append("\n");
    sb.append("    decimalPoint: ").append(toIndentedString(decimalPoint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

