/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")

public class SendTaskValidationResults
{
  public static final String SERIALIZED_NAME_VALIDATION_RESULTS = "validationResults";
  @SerializedName(SERIALIZED_NAME_VALIDATION_RESULTS)
  private List<ValidationResult> validationResults = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_ELEMENTS = "elements";
  @SerializedName(SERIALIZED_NAME_ELEMENTS)
  private List<BaseValidationResults> elements = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TOPIC = "topic";
  @SerializedName(SERIALIZED_NAME_TOPIC)
  private String topic;

  public static final String SERIALIZED_NAME_INCOMING = "incoming";
  @SerializedName(SERIALIZED_NAME_INCOMING)
  private String incoming;

  public static final String SERIALIZED_NAME_OUTGOING = "outgoing";
  @SerializedName(SERIALIZED_NAME_OUTGOING)
  private String outgoing;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private String template;

  public static final String SERIALIZED_NAME_RECIPIENTS = "recipients";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS)
  private String recipients;


  public SendTaskValidationResults validationResults(List<ValidationResult> validationResults)
  {

    this.validationResults = validationResults;
    return this;
  }

  public SendTaskValidationResults addValidationResultsItem(ValidationResult validationResultsItem)
  {
    if (this.validationResults == null)
    {
      this.validationResults = new ArrayList<ValidationResult>();
    }
    this.validationResults.add(validationResultsItem);
    return this;
  }

  /**
   * @return validationResults
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ValidationResult> getValidationResults()
  {
    return validationResults;
  }


  public void setValidationResults(List<ValidationResult> validationResults)
  {
    this.validationResults = validationResults;
  }


  public SendTaskValidationResults id(String id)
  {

    this.id = id;
    return this;
  }

  /**
   * @return id
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId()
  {
    return id;
  }


  public void setId(String id)
  {
    this.id = id;
  }


  public SendTaskValidationResults elements(List<BaseValidationResults> elements)
  {

    this.elements = elements;
    return this;
  }

  public SendTaskValidationResults addElementsItem(BaseValidationResults elementsItem)
  {
    if (this.elements == null)
    {
      this.elements = new ArrayList<BaseValidationResults>();
    }
    this.elements.add(elementsItem);
    return this;
  }

  /**
   * @return elements
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BaseValidationResults> getElements()
  {
    return elements;
  }


  public void setElements(List<BaseValidationResults> elements)
  {
    this.elements = elements;
  }


  public SendTaskValidationResults name(String name)
  {

    this.name = name;
    return this;
  }

  /**
   * @return name
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName()
  {
    return name;
  }


  public void setName(String name)
  {
    this.name = name;
  }


  public SendTaskValidationResults topic(String topic)
  {

    this.topic = topic;
    return this;
  }

  /**
   * @return topic
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTopic()
  {
    return topic;
  }


  public void setTopic(String topic)
  {
    this.topic = topic;
  }


  public SendTaskValidationResults incoming(String incoming)
  {

    this.incoming = incoming;
    return this;
  }

  /**
   * @return incoming
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIncoming()
  {
    return incoming;
  }


  public void setIncoming(String incoming)
  {
    this.incoming = incoming;
  }


  public SendTaskValidationResults outgoing(String outgoing)
  {

    this.outgoing = outgoing;
    return this;
  }

  /**
   * @return outgoing
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOutgoing()
  {
    return outgoing;
  }


  public void setOutgoing(String outgoing)
  {
    this.outgoing = outgoing;
  }


  public SendTaskValidationResults template(String template)
  {

    this.template = template;
    return this;
  }

  /**
   * @return template
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTemplate()
  {
    return template;
  }


  public void setTemplate(String template)
  {
    this.template = template;
  }


  public SendTaskValidationResults recipients(String recipients)
  {

    this.recipients = recipients;
    return this;
  }

  /**
   * @return recipients
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRecipients()
  {
    return recipients;
  }


  public void setRecipients(String recipients)
  {
    this.recipients = recipients;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    SendTaskValidationResults sendTaskValidationResults = (SendTaskValidationResults) o;
    return Objects.equals(this.validationResults, sendTaskValidationResults.validationResults) &&
            Objects.equals(this.id, sendTaskValidationResults.id) &&
            Objects.equals(this.elements, sendTaskValidationResults.elements) &&
            Objects.equals(this.name, sendTaskValidationResults.name) &&
            Objects.equals(this.topic, sendTaskValidationResults.topic) &&
            Objects.equals(this.incoming, sendTaskValidationResults.incoming) &&
            Objects.equals(this.outgoing, sendTaskValidationResults.outgoing) &&
            Objects.equals(this.template, sendTaskValidationResults.template) &&
            Objects.equals(this.recipients, sendTaskValidationResults.recipients);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(validationResults, id, elements, name, topic, incoming, outgoing, template, recipients);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendTaskValidationResults {\n");
    sb.append("    validationResults: ").append(toIndentedString(validationResults)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    incoming: ").append(toIndentedString(incoming)).append("\n");
    sb.append("    outgoing: ").append(toIndentedString(outgoing)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

