/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SingleSelectColumnDtoAllOf
 */

public class SingleSelectColumnDtoAllOf
{
  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  private Integer width;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private Integer position;

  public static final String SERIALIZED_NAME_STYLE = "style";
  @SerializedName(SERIALIZED_NAME_STYLE)
  private String style;

  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "defaultValue";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  private String defaultValue;

  public static final String SERIALIZED_NAME_FORMER_TECHNICAL_VALUE = "formerTechnicalValue";
  @SerializedName(SERIALIZED_NAME_FORMER_TECHNICAL_VALUE)
  private String formerTechnicalValue;

  public static final String SERIALIZED_NAME_DYNAMIC_TABLE_INDEX = "dynamicTableIndex";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_TABLE_INDEX)
  private String dynamicTableIndex;


  public SingleSelectColumnDtoAllOf width(Integer width)
  {

    this.width = width;
    return this;
  }

  /**
   * @return width
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWidth()
  {
    return width;
  }


  public void setWidth(Integer width)
  {
    this.width = width;
  }


  public SingleSelectColumnDtoAllOf position(Integer position)
  {

    this.position = position;
    return this;
  }

  /**
   * @return position
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPosition()
  {
    return position;
  }


  public void setPosition(Integer position)
  {
    this.position = position;
  }


  public SingleSelectColumnDtoAllOf style(String style)
  {

    this.style = style;
    return this;
  }

  /**
   * @return style
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStyle()
  {
    return style;
  }


  public void setStyle(String style)
  {
    this.style = style;
  }


  public SingleSelectColumnDtoAllOf defaultValue(String defaultValue)
  {

    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * @return defaultValue
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDefaultValue()
  {
    return defaultValue;
  }


  public void setDefaultValue(String defaultValue)
  {
    this.defaultValue = defaultValue;
  }


  public SingleSelectColumnDtoAllOf formerTechnicalValue(String formerTechnicalValue)
  {

    this.formerTechnicalValue = formerTechnicalValue;
    return this;
  }

  /**
   * @return formerTechnicalValue
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFormerTechnicalValue()
  {
    return formerTechnicalValue;
  }


  public void setFormerTechnicalValue(String formerTechnicalValue)
  {
    this.formerTechnicalValue = formerTechnicalValue;
  }


  public SingleSelectColumnDtoAllOf dynamicTableIndex(String dynamicTableIndex)
  {

    this.dynamicTableIndex = dynamicTableIndex;
    return this;
  }

  /**
   * @return dynamicTableIndex
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDynamicTableIndex()
  {
    return dynamicTableIndex;
  }


  public void setDynamicTableIndex(String dynamicTableIndex)
  {
    this.dynamicTableIndex = dynamicTableIndex;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    SingleSelectColumnDtoAllOf singleSelectColumnDtoAllOf = (SingleSelectColumnDtoAllOf) o;
    return Objects.equals(this.width, singleSelectColumnDtoAllOf.width) &&
            Objects.equals(this.position, singleSelectColumnDtoAllOf.position) &&
            Objects.equals(this.style, singleSelectColumnDtoAllOf.style) &&
            Objects.equals(this.defaultValue, singleSelectColumnDtoAllOf.defaultValue) &&
            Objects.equals(this.formerTechnicalValue, singleSelectColumnDtoAllOf.formerTechnicalValue) &&
            Objects.equals(this.dynamicTableIndex, singleSelectColumnDtoAllOf.dynamicTableIndex);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(width, position, style, defaultValue, formerTechnicalValue, dynamicTableIndex);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SingleSelectColumnDtoAllOf {\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    formerTechnicalValue: ").append(toIndentedString(formerTechnicalValue)).append("\n");
    sb.append("    dynamicTableIndex: ").append(toIndentedString(dynamicTableIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

