/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * StepAccessAndRightsDtoAllOf
 */

public class StepAccessAndRightsDtoAllOf
{
  public static final String SERIALIZED_NAME_DEFAULT_DATA_SHEET = "defaultDataSheet";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DATA_SHEET)
  private String defaultDataSheet;


  public StepAccessAndRightsDtoAllOf defaultDataSheet(String defaultDataSheet)
  {

    this.defaultDataSheet = defaultDataSheet;
    return this;
  }

  /**
   * @return defaultDataSheet
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDefaultDataSheet()
  {
    return defaultDataSheet;
  }


  public void setDefaultDataSheet(String defaultDataSheet)
  {
    this.defaultDataSheet = defaultDataSheet;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    StepAccessAndRightsDtoAllOf stepAccessAndRightsDtoAllOf = (StepAccessAndRightsDtoAllOf) o;
    return Objects.equals(this.defaultDataSheet, stepAccessAndRightsDtoAllOf.defaultDataSheet);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(defaultDataSheet);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StepAccessAndRightsDtoAllOf {\n");
    sb.append("    defaultDataSheet: ").append(toIndentedString(defaultDataSheet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

