/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.LocalDate;

import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")

public class TaskTimelineDto
{
  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private LocalDate startDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private LocalDate endDate;

  public static final String SERIALIZED_NAME_JOB_TYPE_ID = "jobTypeId";
  @SerializedName(SERIALIZED_NAME_JOB_TYPE_ID)
  private Integer jobTypeId;

  public static final String SERIALIZED_NAME_JOB_NAME = "jobName";
  @SerializedName(SERIALIZED_NAME_JOB_NAME)
  private String jobName;

  public static final String SERIALIZED_NAME_JOB_TYPE_NAME = "jobTypeName";
  @SerializedName(SERIALIZED_NAME_JOB_TYPE_NAME)
  private String jobTypeName;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ASSIGNEE_ID = "assigneeId";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE_ID)
  private Integer assigneeId;


  public TaskTimelineDto startDate(LocalDate startDate)
  {

    this.startDate = startDate;
    return this;
  }

  /**
   * @return startDate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getStartDate()
  {
    return startDate;
  }


  public void setStartDate(LocalDate startDate)
  {
    this.startDate = startDate;
  }


  public TaskTimelineDto endDate(LocalDate endDate)
  {

    this.endDate = endDate;
    return this;
  }

  /**
   * @return endDate
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getEndDate()
  {
    return endDate;
  }


  public void setEndDate(LocalDate endDate)
  {
    this.endDate = endDate;
  }


  public TaskTimelineDto jobTypeId(Integer jobTypeId)
  {

    this.jobTypeId = jobTypeId;
    return this;
  }

  /**
   * @return jobTypeId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getJobTypeId()
  {
    return jobTypeId;
  }


  public void setJobTypeId(Integer jobTypeId)
  {
    this.jobTypeId = jobTypeId;
  }


  public TaskTimelineDto jobName(String jobName)
  {

    this.jobName = jobName;
    return this;
  }

  /**
   * @return jobName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getJobName()
  {
    return jobName;
  }


  public void setJobName(String jobName)
  {
    this.jobName = jobName;
  }


  public TaskTimelineDto jobTypeName(String jobTypeName)
  {

    this.jobTypeName = jobTypeName;
    return this;
  }

  /**
   * @return jobTypeName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getJobTypeName()
  {
    return jobTypeName;
  }


  public void setJobTypeName(String jobTypeName)
  {
    this.jobTypeName = jobTypeName;
  }


  public TaskTimelineDto name(String name)
  {

    this.name = name;
    return this;
  }

  /**
   * @return name
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName()
  {
    return name;
  }


  public void setName(String name)
  {
    this.name = name;
  }


  public TaskTimelineDto assigneeId(Integer assigneeId)
  {

    this.assigneeId = assigneeId;
    return this;
  }

  /**
   * @return assigneeId
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAssigneeId()
  {
    return assigneeId;
  }


  public void setAssigneeId(Integer assigneeId)
  {
    this.assigneeId = assigneeId;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    TaskTimelineDto taskTimelineDto = (TaskTimelineDto) o;
    return Objects.equals(this.startDate, taskTimelineDto.startDate) &&
            Objects.equals(this.endDate, taskTimelineDto.endDate) &&
            Objects.equals(this.jobTypeId, taskTimelineDto.jobTypeId) &&
            Objects.equals(this.jobName, taskTimelineDto.jobName) &&
            Objects.equals(this.jobTypeName, taskTimelineDto.jobTypeName) &&
            Objects.equals(this.name, taskTimelineDto.name) &&
            Objects.equals(this.assigneeId, taskTimelineDto.assigneeId);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(startDate, endDate, jobTypeId, jobName, jobTypeName, name, assigneeId);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskTimelineDto {\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    jobTypeId: ").append(toIndentedString(jobTypeId)).append("\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    jobTypeName: ").append(toIndentedString(jobTypeName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    assigneeId: ").append(toIndentedString(assigneeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

