/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UnsupportedAttributeErrorAllOf
 */

public class UnsupportedAttributeErrorAllOf
{
  public static final String SERIALIZED_NAME_ATTR_VALUE = "attrValue";
  @SerializedName(SERIALIZED_NAME_ATTR_VALUE)
  private String attrValue;


  public UnsupportedAttributeErrorAllOf attrValue(String attrValue)
  {

    this.attrValue = attrValue;
    return this;
  }

  /**
   * @return attrValue
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAttrValue()
  {
    return attrValue;
  }


  public void setAttrValue(String attrValue)
  {
    this.attrValue = attrValue;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    UnsupportedAttributeErrorAllOf unsupportedAttributeErrorAllOf = (UnsupportedAttributeErrorAllOf) o;
    return Objects.equals(this.attrValue, unsupportedAttributeErrorAllOf.attrValue);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(attrValue);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnsupportedAttributeErrorAllOf {\n");
    sb.append("    attrValue: ").append(toIndentedString(attrValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

