/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")

public class UserSearchParamsDto
{
  public static final String SERIALIZED_NAME_SEARCH = "search";
  @SerializedName(SERIALIZED_NAME_SEARCH)
  private String search;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private Integer offset;

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Integer limit;


  public UserSearchParamsDto search(String search)
  {

    this.search = search;
    return this;
  }

  /**
   * @return search
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSearch()
  {
    return search;
  }


  public void setSearch(String search)
  {
    this.search = search;
  }


  public UserSearchParamsDto offset(Integer offset)
  {

    this.offset = offset;
    return this;
  }

  /**
   * @return offset
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getOffset()
  {
    return offset;
  }


  public void setOffset(Integer offset)
  {
    this.offset = offset;
  }


  public UserSearchParamsDto limit(Integer limit)
  {

    this.limit = limit;
    return this;
  }

  /**
   * @return limit
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getLimit()
  {
    return limit;
  }


  public void setLimit(Integer limit)
  {
    this.limit = limit;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    UserSearchParamsDto userSearchParamsDto = (UserSearchParamsDto) o;
    return Objects.equals(this.search, userSearchParamsDto.search) &&
            Objects.equals(this.offset, userSearchParamsDto.offset) &&
            Objects.equals(this.limit, userSearchParamsDto.limit);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(search, offset, limit);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSearchParamsDto {\n");
    sb.append("    search: ").append(toIndentedString(search)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

