/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")

public class UserViewResultDto
{
  public static final String SERIALIZED_NAME_EXISTS = "exists";
  @SerializedName(SERIALIZED_NAME_EXISTS)
  private Boolean exists;

  public static final String SERIALIZED_NAME_USER_VIEW = "userView";
  @SerializedName(SERIALIZED_NAME_USER_VIEW)
  private UserViewDto userView;


  public UserViewResultDto exists(Boolean exists)
  {

    this.exists = exists;
    return this;
  }

  /**
   * @return exists
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getExists()
  {
    return exists;
  }


  public void setExists(Boolean exists)
  {
    this.exists = exists;
  }


  public UserViewResultDto userView(UserViewDto userView)
  {

    this.userView = userView;
    return this;
  }

  /**
   * Get userView
   *
   * @return userView
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserViewDto getUserView()
  {
    return userView;
  }


  public void setUserView(UserViewDto userView)
  {
    this.userView = userView;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    UserViewResultDto userViewResultDto = (UserViewResultDto) o;
    return Objects.equals(this.exists, userViewResultDto.exists) &&
            Objects.equals(this.userView, userViewResultDto.userView);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(exists, userView);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserViewResultDto {\n");
    sb.append("    exists: ").append(toIndentedString(exists)).append("\n");
    sb.append("    userView: ").append(toIndentedString(userView)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

