/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Access rights per owner, creator, etc
 */
@ApiModel(description = "Access rights per owner, creator, etc")

public class VariableTypeAccessibilityAttributesDto
{
  public static final String SERIALIZED_NAME_OWNER_ACCESSIBILITY_TYPE = "ownerAccessibilityType";
  @SerializedName(SERIALIZED_NAME_OWNER_ACCESSIBILITY_TYPE)
  private Integer ownerAccessibilityType;

  public static final String SERIALIZED_NAME_CREATOR_ACCESSIBILITY_TYPE = "creatorAccessibilityType";
  @SerializedName(SERIALIZED_NAME_CREATOR_ACCESSIBILITY_TYPE)
  private Integer creatorAccessibilityType;

  public static final String SERIALIZED_NAME_OTHER_ACCESSIBILITY_TYPE = "otherAccessibilityType";
  @SerializedName(SERIALIZED_NAME_OTHER_ACCESSIBILITY_TYPE)
  private Integer otherAccessibilityType;

  public static final String SERIALIZED_NAME_ANONYMOUS_ACCESSIBILITY_TYPE = "anonymousAccessibilityType";
  @SerializedName(SERIALIZED_NAME_ANONYMOUS_ACCESSIBILITY_TYPE)
  private Integer anonymousAccessibilityType;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "contentType";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private Integer contentType;


  public VariableTypeAccessibilityAttributesDto ownerAccessibilityType(Integer ownerAccessibilityType)
  {

    this.ownerAccessibilityType = ownerAccessibilityType;
    return this;
  }

  /**
   * Owner accessibility (1-Invisible,  2-Readable,  3-Changeable/Displayed)
   *
   * @return ownerAccessibilityType
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Owner accessibility (1-Invisible,  2-Readable,  3-Changeable/Displayed)")

  public Integer getOwnerAccessibilityType()
  {
    return ownerAccessibilityType;
  }


  public void setOwnerAccessibilityType(Integer ownerAccessibilityType)
  {
    this.ownerAccessibilityType = ownerAccessibilityType;
  }


  public VariableTypeAccessibilityAttributesDto creatorAccessibilityType(Integer creatorAccessibilityType)
  {

    this.creatorAccessibilityType = creatorAccessibilityType;
    return this;
  }

  /**
   * Creator accessibility (1-Invisible, 2-Readable, 3-Changeable/Displayed)
   *
   * @return creatorAccessibilityType
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Creator accessibility (1-Invisible, 2-Readable, 3-Changeable/Displayed)")

  public Integer getCreatorAccessibilityType()
  {
    return creatorAccessibilityType;
  }


  public void setCreatorAccessibilityType(Integer creatorAccessibilityType)
  {
    this.creatorAccessibilityType = creatorAccessibilityType;
  }


  public VariableTypeAccessibilityAttributesDto otherAccessibilityType(Integer otherAccessibilityType)
  {

    this.otherAccessibilityType = otherAccessibilityType;
    return this;
  }

  /**
   * Other participants accessibility (1-Invisible, 2-Readable, 3-Changeable/Displayed)
   *
   * @return otherAccessibilityType
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Other participants accessibility (1-Invisible, 2-Readable, 3-Changeable/Displayed)")

  public Integer getOtherAccessibilityType()
  {
    return otherAccessibilityType;
  }


  public void setOtherAccessibilityType(Integer otherAccessibilityType)
  {
    this.otherAccessibilityType = otherAccessibilityType;
  }


  public VariableTypeAccessibilityAttributesDto anonymousAccessibilityType(Integer anonymousAccessibilityType)
  {

    this.anonymousAccessibilityType = anonymousAccessibilityType;
    return this;
  }

  /**
   * Anonymous accessibility (1-Invisible, 2-Readable)
   *
   * @return anonymousAccessibilityType
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Anonymous accessibility (1-Invisible, 2-Readable)")

  public Integer getAnonymousAccessibilityType()
  {
    return anonymousAccessibilityType;
  }


  public void setAnonymousAccessibilityType(Integer anonymousAccessibilityType)
  {
    this.anonymousAccessibilityType = anonymousAccessibilityType;
  }


  public VariableTypeAccessibilityAttributesDto contentType(Integer contentType)
  {

    this.contentType = contentType;
    return this;
  }

  /**
   * content type for owner&#39;s accessibility (1-can be empty, 2 - required)
   *
   * @return contentType
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "content type for owner's accessibility (1-can be empty, 2 - required)")

  public Integer getContentType()
  {
    return contentType;
  }


  public void setContentType(Integer contentType)
  {
    this.contentType = contentType;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    VariableTypeAccessibilityAttributesDto variableTypeAccessibilityAttributesDto = (VariableTypeAccessibilityAttributesDto) o;
    return Objects.equals(this.ownerAccessibilityType, variableTypeAccessibilityAttributesDto.ownerAccessibilityType) &&
            Objects.equals(this.creatorAccessibilityType, variableTypeAccessibilityAttributesDto.creatorAccessibilityType) &&
            Objects.equals(this.otherAccessibilityType, variableTypeAccessibilityAttributesDto.otherAccessibilityType) &&
            Objects.equals(this.anonymousAccessibilityType, variableTypeAccessibilityAttributesDto.anonymousAccessibilityType) &&
            Objects.equals(this.contentType, variableTypeAccessibilityAttributesDto.contentType);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(ownerAccessibilityType, creatorAccessibilityType, otherAccessibilityType, anonymousAccessibilityType, contentType);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableTypeAccessibilityAttributesDto {\n");
    sb.append("    ownerAccessibilityType: ").append(toIndentedString(ownerAccessibilityType)).append("\n");
    sb.append("    creatorAccessibilityType: ").append(toIndentedString(creatorAccessibilityType)).append("\n");
    sb.append("    otherAccessibilityType: ").append(toIndentedString(otherAccessibilityType)).append("\n");
    sb.append("    anonymousAccessibilityType: ").append(toIndentedString(anonymousAccessibilityType)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

