/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.LocalDate;

/**
 *
 */
@ApiModel(description = "")

public class WorkflowStepTimelineDto
{
    public static final String SERIALIZED_NAME_START_DATE = "startDate";
    @SerializedName(SERIALIZED_NAME_START_DATE)
    private LocalDate startDate;

    public static final String SERIALIZED_NAME_END_DATE = "endDate";
    @SerializedName(SERIALIZED_NAME_END_DATE)
    private LocalDate endDate;

    public static final String SERIALIZED_NAME_JOB_TYPE_ID = "jobTypeId";
    @SerializedName(SERIALIZED_NAME_JOB_TYPE_ID)
    private Integer jobTypeId;

    public static final String SERIALIZED_NAME_JOB_NAME = "jobName";
    @SerializedName(SERIALIZED_NAME_JOB_NAME)
    private String jobName;

    public static final String SERIALIZED_NAME_JOB_TYPE_NAME = "jobTypeName";
    @SerializedName(SERIALIZED_NAME_JOB_TYPE_NAME)
    private String jobTypeName;

    public static final String SERIALIZED_NAME_WORKFLOW_OBJECT_ID = "workflowObjectId";
    @SerializedName(SERIALIZED_NAME_WORKFLOW_OBJECT_ID)
    private Integer workflowObjectId;

    public static final String SERIALIZED_NAME_WORKFLOW_STEP_TEMPLATE_ID = "workflowStepTemplateId";
    @SerializedName(SERIALIZED_NAME_WORKFLOW_STEP_TEMPLATE_ID)
    private Integer workflowStepTemplateId;

    public static final String SERIALIZED_NAME_CURRENT_WORKFLOW_STEP = "currentWorkflowStep";
    @SerializedName(SERIALIZED_NAME_CURRENT_WORKFLOW_STEP)
    private Boolean currentWorkflowStep;


    public WorkflowStepTimelineDto startDate(LocalDate startDate)
    {

        this.startDate = startDate;
        return this;
    }

    /**
     * @return startDate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public LocalDate getStartDate()
    {
        return startDate;
    }


    public void setStartDate(LocalDate startDate)
    {
        this.startDate = startDate;
    }


    public WorkflowStepTimelineDto endDate(LocalDate endDate)
    {

        this.endDate = endDate;
        return this;
    }

    /**
     * @return endDate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public LocalDate getEndDate()
    {
        return endDate;
    }


    public void setEndDate(LocalDate endDate)
    {
        this.endDate = endDate;
    }


    public WorkflowStepTimelineDto jobTypeId(Integer jobTypeId)
    {

        this.jobTypeId = jobTypeId;
        return this;
    }

    /**
     * @return jobTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getJobTypeId()
    {
        return jobTypeId;
    }


    public void setJobTypeId(Integer jobTypeId)
    {
        this.jobTypeId = jobTypeId;
    }


    public WorkflowStepTimelineDto jobName(String jobName)
    {

        this.jobName = jobName;
        return this;
    }

    /**
     * @return jobName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getJobName()
    {
        return jobName;
    }


    public void setJobName(String jobName)
    {
        this.jobName = jobName;
    }


    public WorkflowStepTimelineDto jobTypeName(String jobTypeName)
    {

        this.jobTypeName = jobTypeName;
        return this;
    }

    /**
     * @return jobTypeName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getJobTypeName()
    {
        return jobTypeName;
    }


    public void setJobTypeName(String jobTypeName)
    {
        this.jobTypeName = jobTypeName;
    }


    public WorkflowStepTimelineDto workflowObjectId(Integer workflowObjectId)
    {

        this.workflowObjectId = workflowObjectId;
        return this;
    }

    /**
     * @return workflowObjectId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWorkflowObjectId()
    {
        return workflowObjectId;
    }


    public void setWorkflowObjectId(Integer workflowObjectId)
    {
        this.workflowObjectId = workflowObjectId;
    }


    public WorkflowStepTimelineDto workflowStepTemplateId(Integer workflowStepTemplateId)
    {

        this.workflowStepTemplateId = workflowStepTemplateId;
        return this;
    }

    /**
     * @return workflowStepTemplateId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWorkflowStepTemplateId()
    {
        return workflowStepTemplateId;
    }


    public void setWorkflowStepTemplateId(Integer workflowStepTemplateId)
    {
        this.workflowStepTemplateId = workflowStepTemplateId;
    }


    public WorkflowStepTimelineDto currentWorkflowStep(Boolean currentWorkflowStep)
    {

        this.currentWorkflowStep = currentWorkflowStep;
        return this;
    }

    /**
     * @return currentWorkflowStep
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getCurrentWorkflowStep()
    {
        return currentWorkflowStep;
    }


    public void setCurrentWorkflowStep(Boolean currentWorkflowStep)
    {
        this.currentWorkflowStep = currentWorkflowStep;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        WorkflowStepTimelineDto workflowStepTimelineDto = (WorkflowStepTimelineDto) o;
        return Objects.equals(this.startDate, workflowStepTimelineDto.startDate) &&
                Objects.equals(this.endDate, workflowStepTimelineDto.endDate) &&
                Objects.equals(this.jobTypeId, workflowStepTimelineDto.jobTypeId) &&
                Objects.equals(this.jobName, workflowStepTimelineDto.jobName) &&
                Objects.equals(this.jobTypeName, workflowStepTimelineDto.jobTypeName) &&
                Objects.equals(this.workflowObjectId, workflowStepTimelineDto.workflowObjectId) &&
                Objects.equals(this.workflowStepTemplateId, workflowStepTimelineDto.workflowStepTemplateId) &&
                Objects.equals(this.currentWorkflowStep, workflowStepTimelineDto.currentWorkflowStep);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(startDate, endDate, jobTypeId, jobName, jobTypeName, workflowObjectId, workflowStepTemplateId, currentWorkflowStep);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class WorkflowStepTimelineDto {\n");
        sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
        sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
        sb.append("    jobTypeId: ").append(toIndentedString(jobTypeId)).append("\n");
        sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
        sb.append("    jobTypeName: ").append(toIndentedString(jobTypeName)).append("\n");
        sb.append("    workflowObjectId: ").append(toIndentedString(workflowObjectId)).append("\n");
        sb.append("    workflowStepTemplateId: ").append(toIndentedString(workflowStepTemplateId)).append("\n");
        sb.append("    currentWorkflowStep: ").append(toIndentedString(currentWorkflowStep)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

