/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * WorkflowObjectAllOf
 */

public class WorkflowObjectAllOf
{
    public static final String SERIALIZED_NAME_WORKFLOW_TYPE = "workflowType";
    @SerializedName(SERIALIZED_NAME_WORKFLOW_TYPE)
    private WorkflowType workflowType;

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    private String type;


    public WorkflowObjectAllOf workflowType(WorkflowType workflowType)
    {

        this.workflowType = workflowType;
        return this;
    }

    /**
     * Get workflowType
     *
     * @return workflowType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public WorkflowType getWorkflowType()
    {
        return workflowType;
    }


    public void setWorkflowType(WorkflowType workflowType)
    {
        this.workflowType = workflowType;
    }


    public WorkflowObjectAllOf type(String type)
    {

        this.type = type;
        return this;
    }

    /**
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getType()
    {
        return type;
    }


    public void setType(String type)
    {
        this.type = type;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        WorkflowObjectAllOf workflowObjectAllOf = (WorkflowObjectAllOf) o;
        return Objects.equals(this.workflowType, workflowObjectAllOf.workflowType) &&
                Objects.equals(this.type, workflowObjectAllOf.type);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(workflowType, type);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class WorkflowObjectAllOf {\n");
        sb.append("    workflowType: ").append(toIndentedString(workflowType)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

