/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 *
 */
@ApiModel(description = "")

public class WsAdditionalArea
{
    public static final String SERIALIZED_NAME_WS_ADDITIONAL_AREA_ID = "wsAdditionalAreaId";
    @SerializedName(SERIALIZED_NAME_WS_ADDITIONAL_AREA_ID)
    private Integer wsAdditionalAreaId;

    public static final String SERIALIZED_NAME_WS_TEMPLATE_ID = "wsTemplateId";
    @SerializedName(SERIALIZED_NAME_WS_TEMPLATE_ID)
    private Integer wsTemplateId;

    public static final String SERIALIZED_NAME_WS_AREA_ID = "wsAreaId";
    @SerializedName(SERIALIZED_NAME_WS_AREA_ID)
    private Integer wsAreaId;


    public WsAdditionalArea wsAdditionalAreaId(Integer wsAdditionalAreaId)
    {

        this.wsAdditionalAreaId = wsAdditionalAreaId;
        return this;
    }

    /**
     * @return wsAdditionalAreaId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWsAdditionalAreaId()
    {
        return wsAdditionalAreaId;
    }


    public void setWsAdditionalAreaId(Integer wsAdditionalAreaId)
    {
        this.wsAdditionalAreaId = wsAdditionalAreaId;
    }


    public WsAdditionalArea wsTemplateId(Integer wsTemplateId)
    {

        this.wsTemplateId = wsTemplateId;
        return this;
    }

    /**
     * @return wsTemplateId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWsTemplateId()
    {
        return wsTemplateId;
    }


    public void setWsTemplateId(Integer wsTemplateId)
    {
        this.wsTemplateId = wsTemplateId;
    }


    public WsAdditionalArea wsAreaId(Integer wsAreaId)
    {

        this.wsAreaId = wsAreaId;
        return this;
    }

    /**
     * @return wsAreaId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWsAreaId()
    {
        return wsAreaId;
    }


    public void setWsAreaId(Integer wsAreaId)
    {
        this.wsAreaId = wsAreaId;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        WsAdditionalArea wsAdditionalArea = (WsAdditionalArea) o;
        return Objects.equals(this.wsAdditionalAreaId, wsAdditionalArea.wsAdditionalAreaId) &&
                Objects.equals(this.wsTemplateId, wsAdditionalArea.wsTemplateId) &&
                Objects.equals(this.wsAreaId, wsAdditionalArea.wsAreaId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(wsAdditionalAreaId, wsTemplateId, wsAreaId);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class WsAdditionalArea {\n");
        sb.append("    wsAdditionalAreaId: ").append(toIndentedString(wsAdditionalAreaId)).append("\n");
        sb.append("    wsTemplateId: ").append(toIndentedString(wsTemplateId)).append("\n");
        sb.append("    wsAreaId: ").append(toIndentedString(wsAreaId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

