/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 *
 */
@ApiModel(description = "")

public class WsAdditionalAreaDefaultAssignee
{
    public static final String SERIALIZED_NAME_WS_ADDITIONAL_AREA_DEFAULT_ASSIGNEE_ID = "wsAdditionalAreaDefaultAssigneeId";
    @SerializedName(SERIALIZED_NAME_WS_ADDITIONAL_AREA_DEFAULT_ASSIGNEE_ID)
    private Integer wsAdditionalAreaDefaultAssigneeId;

    public static final String SERIALIZED_NAME_WS_DEFAULT_APPROVING_USER_ID = "wsDefaultApprovingUserId";
    @SerializedName(SERIALIZED_NAME_WS_DEFAULT_APPROVING_USER_ID)
    private Integer wsDefaultApprovingUserId;

    public static final String SERIALIZED_NAME_WS_ADDITIONAL_AREA_ID = "wsAdditionalAreaId";
    @SerializedName(SERIALIZED_NAME_WS_ADDITIONAL_AREA_ID)
    private Integer wsAdditionalAreaId;

    public static final String SERIALIZED_NAME_WORKFLOW_OBJECT_ID = "workflowObjectId";
    @SerializedName(SERIALIZED_NAME_WORKFLOW_OBJECT_ID)
    private Integer workflowObjectId;


    public WsAdditionalAreaDefaultAssignee wsAdditionalAreaDefaultAssigneeId(Integer wsAdditionalAreaDefaultAssigneeId)
    {

        this.wsAdditionalAreaDefaultAssigneeId = wsAdditionalAreaDefaultAssigneeId;
        return this;
    }

    /**
     * @return wsAdditionalAreaDefaultAssigneeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWsAdditionalAreaDefaultAssigneeId()
    {
        return wsAdditionalAreaDefaultAssigneeId;
    }


    public void setWsAdditionalAreaDefaultAssigneeId(Integer wsAdditionalAreaDefaultAssigneeId)
    {
        this.wsAdditionalAreaDefaultAssigneeId = wsAdditionalAreaDefaultAssigneeId;
    }


    public WsAdditionalAreaDefaultAssignee wsDefaultApprovingUserId(Integer wsDefaultApprovingUserId)
    {

        this.wsDefaultApprovingUserId = wsDefaultApprovingUserId;
        return this;
    }

    /**
     * @return wsDefaultApprovingUserId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWsDefaultApprovingUserId()
    {
        return wsDefaultApprovingUserId;
    }


    public void setWsDefaultApprovingUserId(Integer wsDefaultApprovingUserId)
    {
        this.wsDefaultApprovingUserId = wsDefaultApprovingUserId;
    }


    public WsAdditionalAreaDefaultAssignee wsAdditionalAreaId(Integer wsAdditionalAreaId)
    {

        this.wsAdditionalAreaId = wsAdditionalAreaId;
        return this;
    }

    /**
     * @return wsAdditionalAreaId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWsAdditionalAreaId()
    {
        return wsAdditionalAreaId;
    }


    public void setWsAdditionalAreaId(Integer wsAdditionalAreaId)
    {
        this.wsAdditionalAreaId = wsAdditionalAreaId;
    }


    public WsAdditionalAreaDefaultAssignee workflowObjectId(Integer workflowObjectId)
    {

        this.workflowObjectId = workflowObjectId;
        return this;
    }

    /**
     * @return workflowObjectId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getWorkflowObjectId()
    {
        return workflowObjectId;
    }


    public void setWorkflowObjectId(Integer workflowObjectId)
    {
        this.workflowObjectId = workflowObjectId;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        WsAdditionalAreaDefaultAssignee wsAdditionalAreaDefaultAssignee = (WsAdditionalAreaDefaultAssignee) o;
        return Objects.equals(this.wsAdditionalAreaDefaultAssigneeId, wsAdditionalAreaDefaultAssignee.wsAdditionalAreaDefaultAssigneeId) &&
                Objects.equals(this.wsDefaultApprovingUserId, wsAdditionalAreaDefaultAssignee.wsDefaultApprovingUserId) &&
                Objects.equals(this.wsAdditionalAreaId, wsAdditionalAreaDefaultAssignee.wsAdditionalAreaId) &&
                Objects.equals(this.workflowObjectId, wsAdditionalAreaDefaultAssignee.workflowObjectId);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(wsAdditionalAreaDefaultAssigneeId, wsDefaultApprovingUserId, wsAdditionalAreaId, workflowObjectId);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class WsAdditionalAreaDefaultAssignee {\n");
        sb.append("    wsAdditionalAreaDefaultAssigneeId: ").append(toIndentedString(wsAdditionalAreaDefaultAssigneeId)).append("\n");
        sb.append("    wsDefaultApprovingUserId: ").append(toIndentedString(wsDefaultApprovingUserId)).append("\n");
        sb.append("    wsAdditionalAreaId: ").append(toIndentedString(wsAdditionalAreaId)).append("\n");
        sb.append("    workflowObjectId: ").append(toIndentedString(workflowObjectId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

