/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * DTO for Web-to-Publish variable type.
 */
@ApiModel(description = "DTO for Web-to-Publish variable type.")

public class WtpTemplateDto
{
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;

    public static final String SERIALIZED_NAME_META_TYPE_ID = "metaTypeId";
    @SerializedName(SERIALIZED_NAME_META_TYPE_ID)
    private Integer metaTypeId;

    public static final String SERIALIZED_NAME_META_TYPE_NAME = "metaTypeName";
    @SerializedName(SERIALIZED_NAME_META_TYPE_NAME)
    private String metaTypeName;

    public static final String SERIALIZED_NAME_UNIQUE_NAME = "uniqueName";
    @SerializedName(SERIALIZED_NAME_UNIQUE_NAME)
    private String uniqueName;

    public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
    @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
    private String displayName;

    public static final String SERIALIZED_NAME_RAW_LABEL = "rawLabel";
    @SerializedName(SERIALIZED_NAME_RAW_LABEL)
    private String rawLabel;

    public static final String SERIALIZED_NAME_MODE = "mode";
    @SerializedName(SERIALIZED_NAME_MODE)
    private Integer mode;

    public static final String SERIALIZED_NAME_TECHNICAL_NAME = "technicalName";
    @SerializedName(SERIALIZED_NAME_TECHNICAL_NAME)
    private String technicalName;

    public static final String SERIALIZED_NAME_SHARED_LOCALE = "sharedLocale";
    @SerializedName(SERIALIZED_NAME_SHARED_LOCALE)
    private Boolean sharedLocale;

    public static final String SERIALIZED_NAME_HELP_TEXT = "helpText";
    @SerializedName(SERIALIZED_NAME_HELP_TEXT)
    private String helpText;

    public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
    @SerializedName(SERIALIZED_NAME_VISIBILITY)
    private VisibilityDto visibility;

    public static final String SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_ID = "dependsFromVariableId";
    @SerializedName(SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_ID)
    private Integer dependsFromVariableId;

    public static final String SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_VALUES = "dependsFromVariableValues";
    @SerializedName(SERIALIZED_NAME_DEPENDS_FROM_VARIABLE_VALUES)
    private List<String> dependsFromVariableValues = null;

    public static final String SERIALIZED_NAME_TYPE_SPANNING = "typeSpanning";
    @SerializedName(SERIALIZED_NAME_TYPE_SPANNING)
    private Boolean typeSpanning;

    public static final String SERIALIZED_NAME_SYSTEM = "system";
    @SerializedName(SERIALIZED_NAME_SYSTEM)
    private Boolean system;

    public static final String SERIALIZED_NAME_STORAGE_TYPE = "storageType";
    @SerializedName(SERIALIZED_NAME_STORAGE_TYPE)
    private Integer storageType;

    public static final String SERIALIZED_NAME_TEMPLATE_ID = "templateId";
    @SerializedName(SERIALIZED_NAME_TEMPLATE_ID)
    private Integer templateId;

    public static final String SERIALIZED_NAME_INHERIT_FROM_PARENT = "inheritFromParent";
    @SerializedName(SERIALIZED_NAME_INHERIT_FROM_PARENT)
    private Boolean inheritFromParent;

    public static final String SERIALIZED_NAME_METADATA = "metadata";
    @SerializedName(SERIALIZED_NAME_METADATA)
    private List<WtpTemplateVariableMetadataDto> metadata = null;

    public static final String SERIALIZED_NAME_PREVIEW_ID = "previewId";
    @SerializedName(SERIALIZED_NAME_PREVIEW_ID)
    private Integer previewId;

    public static final String SERIALIZED_NAME_IS_HTML_TEMPLATE = "isHtmlTemplate";
    @SerializedName(SERIALIZED_NAME_IS_HTML_TEMPLATE)
    private Boolean isHtmlTemplate;

    public static final String SERIALIZED_NAME_PREVIEW_VERSION = "previewVersion";
    @SerializedName(SERIALIZED_NAME_PREVIEW_VERSION)
    private Integer previewVersion;


    public WtpTemplateDto id(Integer id)
    {

        this.id = id;
        return this;
    }

    /**
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getId()
    {
        return id;
    }


    public void setId(Integer id)
    {
        this.id = id;
    }


    public WtpTemplateDto metaTypeId(Integer metaTypeId)
    {

        this.metaTypeId = metaTypeId;
        return this;
    }

    /**
     * @return metaTypeId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMetaTypeId()
    {
        return metaTypeId;
    }


    public void setMetaTypeId(Integer metaTypeId)
    {
        this.metaTypeId = metaTypeId;
    }


    public WtpTemplateDto metaTypeName(String metaTypeName)
    {

        this.metaTypeName = metaTypeName;
        return this;
    }

    /**
     * @return metaTypeName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getMetaTypeName()
    {
        return metaTypeName;
    }


    public void setMetaTypeName(String metaTypeName)
    {
        this.metaTypeName = metaTypeName;
    }


    public WtpTemplateDto uniqueName(String uniqueName)
    {

        this.uniqueName = uniqueName;
        return this;
    }

    /**
     * @return uniqueName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getUniqueName()
    {
        return uniqueName;
    }


    public void setUniqueName(String uniqueName)
    {
        this.uniqueName = uniqueName;
    }


    public WtpTemplateDto displayName(String displayName)
    {

        this.displayName = displayName;
        return this;
    }

    /**
     * @return displayName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getDisplayName()
    {
        return displayName;
    }


    public void setDisplayName(String displayName)
    {
        this.displayName = displayName;
    }


    public WtpTemplateDto rawLabel(String rawLabel)
    {

        this.rawLabel = rawLabel;
        return this;
    }

    /**
     * @return rawLabel
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getRawLabel()
    {
        return rawLabel;
    }


    public void setRawLabel(String rawLabel)
    {
        this.rawLabel = rawLabel;
    }


    public WtpTemplateDto mode(Integer mode)
    {

        this.mode = mode;
        return this;
    }

    /**
     * @return mode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getMode()
    {
        return mode;
    }


    public void setMode(Integer mode)
    {
        this.mode = mode;
    }


    public WtpTemplateDto technicalName(String technicalName)
    {

        this.technicalName = technicalName;
        return this;
    }

    /**
     * @return technicalName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getTechnicalName()
    {
        return technicalName;
    }


    public void setTechnicalName(String technicalName)
    {
        this.technicalName = technicalName;
    }


    public WtpTemplateDto sharedLocale(Boolean sharedLocale)
    {

        this.sharedLocale = sharedLocale;
        return this;
    }

    /**
     * @return sharedLocale
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getSharedLocale()
    {
        return sharedLocale;
    }


    public void setSharedLocale(Boolean sharedLocale)
    {
        this.sharedLocale = sharedLocale;
    }


    public WtpTemplateDto helpText(String helpText)
    {

        this.helpText = helpText;
        return this;
    }

    /**
     * @return helpText
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getHelpText()
    {
        return helpText;
    }


    public void setHelpText(String helpText)
    {
        this.helpText = helpText;
    }


    public WtpTemplateDto visibility(VisibilityDto visibility)
    {

        this.visibility = visibility;
        return this;
    }

    /**
     * Get visibility
     *
     * @return visibility
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public VisibilityDto getVisibility()
    {
        return visibility;
    }


    public void setVisibility(VisibilityDto visibility)
    {
        this.visibility = visibility;
    }


    public WtpTemplateDto dependsFromVariableId(Integer dependsFromVariableId)
    {

        this.dependsFromVariableId = dependsFromVariableId;
        return this;
    }

    /**
     * @return dependsFromVariableId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getDependsFromVariableId()
    {
        return dependsFromVariableId;
    }


    public void setDependsFromVariableId(Integer dependsFromVariableId)
    {
        this.dependsFromVariableId = dependsFromVariableId;
    }


    public WtpTemplateDto dependsFromVariableValues(List<String> dependsFromVariableValues)
    {

        this.dependsFromVariableValues = dependsFromVariableValues;
        return this;
    }

    public WtpTemplateDto addDependsFromVariableValuesItem(String dependsFromVariableValuesItem)
    {
        if (this.dependsFromVariableValues == null)
        {
            this.dependsFromVariableValues = new ArrayList<String>();
        }
        this.dependsFromVariableValues.add(dependsFromVariableValuesItem);
        return this;
    }

    /**
     * @return dependsFromVariableValues
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<String> getDependsFromVariableValues()
    {
        return dependsFromVariableValues;
    }


    public void setDependsFromVariableValues(List<String> dependsFromVariableValues)
    {
        this.dependsFromVariableValues = dependsFromVariableValues;
    }


    public WtpTemplateDto typeSpanning(Boolean typeSpanning)
    {

        this.typeSpanning = typeSpanning;
        return this;
    }

    /**
     * @return typeSpanning
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getTypeSpanning()
    {
        return typeSpanning;
    }


    public void setTypeSpanning(Boolean typeSpanning)
    {
        this.typeSpanning = typeSpanning;
    }


    public WtpTemplateDto system(Boolean system)
    {

        this.system = system;
        return this;
    }

    /**
     * @return system
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getSystem()
    {
        return system;
    }


    public void setSystem(Boolean system)
    {
        this.system = system;
    }


    public WtpTemplateDto storageType(Integer storageType)
    {

        this.storageType = storageType;
        return this;
    }

    /**
     * @return storageType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getStorageType()
    {
        return storageType;
    }


    public void setStorageType(Integer storageType)
    {
        this.storageType = storageType;
    }


    public WtpTemplateDto templateId(Integer templateId)
    {

        this.templateId = templateId;
        return this;
    }

    /**
     * @return templateId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getTemplateId()
    {
        return templateId;
    }


    public void setTemplateId(Integer templateId)
    {
        this.templateId = templateId;
    }


    public WtpTemplateDto inheritFromParent(Boolean inheritFromParent)
    {

        this.inheritFromParent = inheritFromParent;
        return this;
    }

    /**
     * @return inheritFromParent
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getInheritFromParent()
    {
        return inheritFromParent;
    }


    public void setInheritFromParent(Boolean inheritFromParent)
    {
        this.inheritFromParent = inheritFromParent;
    }


    public WtpTemplateDto metadata(List<WtpTemplateVariableMetadataDto> metadata)
    {

        this.metadata = metadata;
        return this;
    }

    public WtpTemplateDto addMetadataItem(WtpTemplateVariableMetadataDto metadataItem)
    {
        if (this.metadata == null)
        {
            this.metadata = new ArrayList<WtpTemplateVariableMetadataDto>();
        }
        this.metadata.add(metadataItem);
        return this;
    }

    /**
     * @return metadata
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<WtpTemplateVariableMetadataDto> getMetadata()
    {
        return metadata;
    }


    public void setMetadata(List<WtpTemplateVariableMetadataDto> metadata)
    {
        this.metadata = metadata;
    }


    public WtpTemplateDto previewId(Integer previewId)
    {

        this.previewId = previewId;
        return this;
    }

    /**
     * @return previewId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getPreviewId()
    {
        return previewId;
    }


    public void setPreviewId(Integer previewId)
    {
        this.previewId = previewId;
    }


    public WtpTemplateDto isHtmlTemplate(Boolean isHtmlTemplate)
    {

        this.isHtmlTemplate = isHtmlTemplate;
        return this;
    }

    /**
     * @return isHtmlTemplate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getIsHtmlTemplate()
    {
        return isHtmlTemplate;
    }


    public void setIsHtmlTemplate(Boolean isHtmlTemplate)
    {
        this.isHtmlTemplate = isHtmlTemplate;
    }


    public WtpTemplateDto previewVersion(Integer previewVersion)
    {

        this.previewVersion = previewVersion;
        return this;
    }

    /**
     * @return previewVersion
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getPreviewVersion()
    {
        return previewVersion;
    }


    public void setPreviewVersion(Integer previewVersion)
    {
        this.previewVersion = previewVersion;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        WtpTemplateDto wtpTemplateDto = (WtpTemplateDto) o;
        return Objects.equals(this.id, wtpTemplateDto.id) &&
                Objects.equals(this.metaTypeId, wtpTemplateDto.metaTypeId) &&
                Objects.equals(this.metaTypeName, wtpTemplateDto.metaTypeName) &&
                Objects.equals(this.uniqueName, wtpTemplateDto.uniqueName) &&
                Objects.equals(this.displayName, wtpTemplateDto.displayName) &&
                Objects.equals(this.rawLabel, wtpTemplateDto.rawLabel) &&
                Objects.equals(this.mode, wtpTemplateDto.mode) &&
                Objects.equals(this.technicalName, wtpTemplateDto.technicalName) &&
                Objects.equals(this.sharedLocale, wtpTemplateDto.sharedLocale) &&
                Objects.equals(this.helpText, wtpTemplateDto.helpText) &&
                Objects.equals(this.visibility, wtpTemplateDto.visibility) &&
                Objects.equals(this.dependsFromVariableId, wtpTemplateDto.dependsFromVariableId) &&
                Objects.equals(this.dependsFromVariableValues, wtpTemplateDto.dependsFromVariableValues) &&
                Objects.equals(this.typeSpanning, wtpTemplateDto.typeSpanning) &&
                Objects.equals(this.system, wtpTemplateDto.system) &&
                Objects.equals(this.storageType, wtpTemplateDto.storageType) &&
                Objects.equals(this.templateId, wtpTemplateDto.templateId) &&
                Objects.equals(this.inheritFromParent, wtpTemplateDto.inheritFromParent) &&
                Objects.equals(this.metadata, wtpTemplateDto.metadata) &&
                Objects.equals(this.previewId, wtpTemplateDto.previewId) &&
                Objects.equals(this.isHtmlTemplate, wtpTemplateDto.isHtmlTemplate) &&
                Objects.equals(this.previewVersion, wtpTemplateDto.previewVersion);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(id, metaTypeId, metaTypeName, uniqueName, displayName, rawLabel, mode, technicalName, sharedLocale, helpText, visibility, dependsFromVariableId, dependsFromVariableValues, typeSpanning, system, storageType, templateId, inheritFromParent, metadata, previewId, isHtmlTemplate, previewVersion);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class WtpTemplateDto {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    metaTypeId: ").append(toIndentedString(metaTypeId)).append("\n");
        sb.append("    metaTypeName: ").append(toIndentedString(metaTypeName)).append("\n");
        sb.append("    uniqueName: ").append(toIndentedString(uniqueName)).append("\n");
        sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
        sb.append("    rawLabel: ").append(toIndentedString(rawLabel)).append("\n");
        sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
        sb.append("    technicalName: ").append(toIndentedString(technicalName)).append("\n");
        sb.append("    sharedLocale: ").append(toIndentedString(sharedLocale)).append("\n");
        sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
        sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
        sb.append("    dependsFromVariableId: ").append(toIndentedString(dependsFromVariableId)).append("\n");
        sb.append("    dependsFromVariableValues: ").append(toIndentedString(dependsFromVariableValues)).append("\n");
        sb.append("    typeSpanning: ").append(toIndentedString(typeSpanning)).append("\n");
        sb.append("    system: ").append(toIndentedString(system)).append("\n");
        sb.append("    storageType: ").append(toIndentedString(storageType)).append("\n");
        sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
        sb.append("    inheritFromParent: ").append(toIndentedString(inheritFromParent)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    previewId: ").append(toIndentedString(previewId)).append("\n");
        sb.append("    isHtmlTemplate: ").append(toIndentedString(isHtmlTemplate)).append("\n");
        sb.append("    previewVersion: ").append(toIndentedString(previewVersion)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

