/*
 * All MRM packages REST API
 * <h2>All MRM packages REST API</h1>
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package admin.api.MRM.externalAPI.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 *
 */
@ApiModel(description = "")

public class XmlNs0VariableVisibilityDto
{
  public static final String SERIALIZED_NAME_VISIBLE_TO_ANONYMOUS = "visibleToAnonymous";
  @SerializedName(SERIALIZED_NAME_VISIBLE_TO_ANONYMOUS)
  private XmlNs0ReadAccessEnum visibleToAnonymous;

  public static final String SERIALIZED_NAME_VISIBLE_TO_ASSIGNEE = "visibleToAssignee";
  @SerializedName(SERIALIZED_NAME_VISIBLE_TO_ASSIGNEE)
  private XmlNs0AssigneeAccessEnum visibleToAssignee;

  public static final String SERIALIZED_NAME_VISIBLE_TO_CREATOR = "visibleToCreator";
  @SerializedName(SERIALIZED_NAME_VISIBLE_TO_CREATOR)
  private XmlNs0ReadAccessEnum visibleToCreator;

  public static final String SERIALIZED_NAME_VISIBLE_TO_OTHERS = "visibleToOthers";
  @SerializedName(SERIALIZED_NAME_VISIBLE_TO_OTHERS)
  private XmlNs0ReadAccessEnum visibleToOthers;


  public XmlNs0VariableVisibilityDto visibleToAnonymous(XmlNs0ReadAccessEnum visibleToAnonymous)
  {

    this.visibleToAnonymous = visibleToAnonymous;
    return this;
  }

  /**
   * Get visibleToAnonymous
   *
   * @return visibleToAnonymous
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public XmlNs0ReadAccessEnum getVisibleToAnonymous()
  {
    return visibleToAnonymous;
  }


  public void setVisibleToAnonymous(XmlNs0ReadAccessEnum visibleToAnonymous)
  {
    this.visibleToAnonymous = visibleToAnonymous;
  }


  public XmlNs0VariableVisibilityDto visibleToAssignee(XmlNs0AssigneeAccessEnum visibleToAssignee)
  {

    this.visibleToAssignee = visibleToAssignee;
    return this;
  }

  /**
   * Get visibleToAssignee
   *
   * @return visibleToAssignee
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public XmlNs0AssigneeAccessEnum getVisibleToAssignee()
  {
    return visibleToAssignee;
  }


  public void setVisibleToAssignee(XmlNs0AssigneeAccessEnum visibleToAssignee)
  {
    this.visibleToAssignee = visibleToAssignee;
  }


  public XmlNs0VariableVisibilityDto visibleToCreator(XmlNs0ReadAccessEnum visibleToCreator)
  {

    this.visibleToCreator = visibleToCreator;
    return this;
  }

  /**
   * Get visibleToCreator
   *
   * @return visibleToCreator
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public XmlNs0ReadAccessEnum getVisibleToCreator()
  {
    return visibleToCreator;
  }


  public void setVisibleToCreator(XmlNs0ReadAccessEnum visibleToCreator)
  {
    this.visibleToCreator = visibleToCreator;
  }


  public XmlNs0VariableVisibilityDto visibleToOthers(XmlNs0ReadAccessEnum visibleToOthers)
  {

    this.visibleToOthers = visibleToOthers;
    return this;
  }

  /**
   * Get visibleToOthers
   *
   * @return visibleToOthers
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public XmlNs0ReadAccessEnum getVisibleToOthers()
  {
    return visibleToOthers;
  }


  public void setVisibleToOthers(XmlNs0ReadAccessEnum visibleToOthers)
  {
    this.visibleToOthers = visibleToOthers;
  }


  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }
    XmlNs0VariableVisibilityDto xmlNs0VariableVisibilityDto = (XmlNs0VariableVisibilityDto) o;
    return Objects.equals(this.visibleToAnonymous, xmlNs0VariableVisibilityDto.visibleToAnonymous) &&
            Objects.equals(this.visibleToAssignee, xmlNs0VariableVisibilityDto.visibleToAssignee) &&
            Objects.equals(this.visibleToCreator, xmlNs0VariableVisibilityDto.visibleToCreator) &&
            Objects.equals(this.visibleToOthers, xmlNs0VariableVisibilityDto.visibleToOthers);
  }

  @Override
  public int hashCode()
  {
    return Objects.hash(visibleToAnonymous, visibleToAssignee, visibleToCreator, visibleToOthers);
  }

  @Override
  public String toString()
  {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmlNs0VariableVisibilityDto {\n");
    sb.append("    visibleToAnonymous: ").append(toIndentedString(visibleToAnonymous)).append("\n");
    sb.append("    visibleToAssignee: ").append(toIndentedString(visibleToAssignee)).append("\n");
    sb.append("    visibleToCreator: ").append(toIndentedString(visibleToCreator)).append("\n");
    sb.append("    visibleToOthers: ").append(toIndentedString(visibleToOthers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o)
  {
    if (o == null)
    {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

